### ISSUE TITLE
trained h5 file

### ISSUE THREAD

**Issue by alighofrani95** [leondgarse/Keras_insightface#1]
thanks a lot for your interesting implementation insight face by Keras

Could you please add to the repo the final trained h5 models?

**Comment by leondgarse** [comment]
I would like to share, but currently I dont have any **final** model.. For **Resnet101** or **Mobilefacenet** model, they are not better than `original` or `gluon-face` project one.
Currenly it's only a `mobilefacenet with se block` model almost able to use... I just uploaded it here [se_mobilefacenet](https://github.com/leondgarse/Keras_insightface/blob/master/checkpoints/keras_se_mobilefacenet_emore_basic_agedb_30_epoch_53_0.956667.h5).

**Comment by sonfire86** [comment]
@leondgarse Can I get the models that you already have?

**Comment by leondgarse** [comment]
@sonfire86 Which one do you want? I'm currently retrainning `se_mobilefacenet` using `Cosine lr decay with restart`. For `ResNeSt101`, I just uploaded one [here in Google drive](https://drive.google.com/file/d/1rG7xqjPbjex_waOPW_1i5ywh9690sBxb/view?usp=sharing). It's accuracy on `agedb_30` is `0.968500`, but the test result in real environment is better than the `0.973333` one.

**Comment by sonfire86** [comment]
@leondgarse I would like EfficientNetB0 and EfficientNetB4. So it’s very low speed on my data

**Comment by leondgarse** [comment]
For me it's also not so good, so I stoppped them long ago...
For `EB0` I only have one trained `5 epochs`, and `EB4` `7 epochs`, the `epoch 54` one got deleted...
I'll try `EB4` again later, but it needs time.
[keras_EB0_emore_basic_agedb_30_epoch_5_0.853333.h5](https://drive.google.com/file/d/1_3X-rcWzS1PnmBzoC_iM7cgjGZgRUieX/view?usp=sharing)
[keras_EB4_emore_basic_agedb_30_epoch_7_0.942000.h5](https://drive.google.com/file/d/1-IaTSWePSzPB9dTSpS0Np1W6ANMejtgk/view?usp=sharing)

**Comment by sonfire86** [comment]
@leondgarse Thank. If I have successful results for B0 I will lay out

**Comment by sonfire86** [comment]
It is not possible to take your weight
```
h5py \ _objects.pyx in h5py._objects.with_phil.wrapper ()
h5py \ _objects.pyx in h5py._objects.with_phil.wrapper ()
h5py \ h5f.pyx in h5py.h5f.open ()
OSError: Unable to open file (file signature not found)
```

**Comment by leondgarse** [comment]
@sonfire86 Sorry i just tested it locally, let me take a check on it...

**Comment by leondgarse** [comment]
@sonfire86 [keras_EB0_emore_basic_agedb_30_epoch_5_0.853333.h5](https://drive.google.com/file/d/18jFbxn2XIWcfsMkIVCWFEvjF-QbWuPcq/view?usp=sharing).
This one is tested with `colab`
```py
!wget -O keras_EB0_emore_basic_agedb_30_epoch_5_0.853333.h5 https://drive.google.com/u/0/uc?id=18jFbxn2XIWcfsMkIVCWFEvjF-QbWuPcq&export=download
from tensorflow import keras
mm = keras.models.load_model("keras_EB0_emore_basic_agedb_30_epoch_5_0.853333.h5", compile=False)
mm.summary()
```

**Comment by sonfire86** [comment]
It`s my problem. TF 1.14 not work

**Comment by leondgarse** [comment]
@sonfire86  Ya, I can only convert `EB0` to `TF 1.15` by  importing layers `Rescaling` `Normalization` from tensorflow source and implementing `swish`, `TF 1.14` is way too far.
```py
import sys
sys.path.append(os.path.expanduser('~/workspace/tensorflow/tensorflow/python/keras/layers/preprocessing/'))
from normalization import Normalization
from image_preprocessing import Rescaling

from tensorflow.keras import backend as K

def swish(inputs):
    return (K.sigmoid(inputs) * inputs)
mm = keras.models.load_model('keras_EB0_emore_basic_agedb_30_epoch_5_0.853333.h5', custom_objects={'swish': swish, "Rescaling": Rescaling, 'Normalization': Normalization})
```

**Comment by sonfire86** [comment]
Can't you put out the weight EfficientNetB4?

**Comment by leondgarse** [comment]
@sonfire86 Sorry, but I'm not trying to keep it private,  I don't have it either... We just compared the inference speed using `TensorRT` and also `android`, the result shows that though the `EfficientNet` models size are smaller, but inference time takes longer.
- [Android test](https://github.com/leondgarse/Keras_insightface#tflite-model-inference-time-test-on-arm32)
- **TensorRT**

| Model       | Size | Timeit            |
| ----------- | ---- | ----------------- |
| EB4         | 72M  | 4.14 ms ± 51.2 µs |
| resnet101v2 | 168M | 3.17 ms ± 21.8 µs |

We are also using a `NPU` board, and `EfficientNet` model performance getting worse comparing `Resnet`..
So we are concentrating on `Mobilenet` and `Resnet` recently.

**Comment by alexandrekj** [comment]
Hi @leondgarse, do you have the trained .h5 files from se_mobilefacenet and mobilefacenet ? 
The previous download links provided are not available anymore.

**Comment by leondgarse** [comment]
Just a not so good one found, and uploaded here [keras_se_mobile_facenet_emore_triplet_basic_agedb_30_epoch_100_0.958333.h5](https://github.com/leondgarse/Keras_insightface/releases/download/v1.0.0/keras_se_mobile_facenet_emore_triplet_basic_agedb_30_epoch_100_0.958333.h5). It's a testing one combining softmax + arcface + triplet training. In those early tests, its accuracy not satisfying, thus we give up on this earlier...
