### ISSUE TITLE
Any hope of having pretrained weights of resnest ?

### ISSUE THREAD

**Issue by ShihuaiXu** [leondgarse/Keras_insightface#10]
thank you in advance

**Comment by leondgarse** [comment]
I have only tried `Resnest101`, and uploaded one [keras_ResNest101_emore_triplet_basic_agedb_30_epoch_96_0.973333.h5](https://drive.google.com/file/d/1RVjTRhE8Evqyjl83EVBMOjInxtDtxGyH/view?usp=sharing), but it's not a very good one.

**Comment by ShihuaiXu** [comment]
Thank you very much
Could you please tell me which dataset you have trained?

**Comment by leondgarse** [comment]
`MS1M-ArcFace` downloaded from [Insightface Dataset Zoo](https://github.com/deepinsight/insightface/wiki/Dataset-Zoo)

**Comment by ShihuaiXu** [comment]
Thanks for your reply, so MS1M-ArcFace dataset is related to human face? I want to the model trained from coco or imagenet.

**Comment by leondgarse** [comment]
Sorry, I don't have that either. The author [Github QiaoranC/tf_ResNeSt_RegNet_model](https://github.com/QiaoranC/tf_ResNeSt_RegNet_model) not providing it , and I didn't try it on `imagenet`.

**Comment by ShihuaiXu** [comment]
Thanks

**Comment by malik-anhar** [comment]
May I know the script you are using to train ResNet101? I wanna train the model using my own dataset. Thank you

**Comment by leondgarse** [comment]
I add a new `discussion` section, please refer here [Training scripts [ResNet101V2]](https://github.com/leondgarse/Keras_insightface/discussions/15).
