### ISSUE TITLE
Research Purposes

### ISSUE THREAD

**Issue by Abdelfatah1998** [leondgarse/Keras_insightface#101]
Hi,
Hope you are doing well.

I am using many of your models in my research and I am fine-tuning the hyperparameters in research that I am working on. I am getting good results atm.
Can we use your models and modify them for our research (with proper citation)?

Thanks!

**Comment by leondgarse** [comment]
Ya sure, it's under the MIT License. There is no limitation for both academic and commercial usage.

**Comment by Abdelfatah1998** [comment]
Noted with thanks.
Appreciate it.
Your work is amazing.
