### ISSUE TITLE
Save the weights after each epoch

### ISSUE THREAD

**Issue by Abdelfatah1998** [leondgarse/Keras_insightface#102]
Hi,
How can I edit the callbacks so that I can also save the weights after each epoch in separate folder or with different file name (so that I can have the weights for each epoch after the training finish)?

Example: Epoch1weigths.h5
Epoch2weights.h5
..
etc

**Comment by leondgarse** [comment]
- For saving model you can set `filepath` for [myCallbacks.py#L261](https://github.com/leondgarse/Keras_insightface/blob/2bc21bfa8fa9c947f3ce7d9a3a37be9e361c45e2/myCallbacks.py#L261) like introduced in [tf.keras.callbacks.ModelCheckpoint](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/ModelCheckpoint):
  ```py
  - model_checkpoint = ModelCheckpoint(checkpoint, verbose=1)
  + model_checkpoint = ModelCheckpoint(os.path.splitext(checkpoint)[0] + "_epoch{epoch:02d}.h5", verbose=1) 
  ```
- For saving basic_model, you can comment off the `os.remove` line in [evals.py#L131-L132](https://github.com/leondgarse/Keras_insightface/blob/master/evals.py#L131-L132).

**Comment by Abdelfatah1998** [comment]
Noted with thanks!
Appreciate it.
