### ISSUE TITLE
Sub Center Loss

### ISSUE THREAD

**Issue by HamDan1999** [leondgarse/Keras_insightface#103]
Hi,
Firstly, your repositories are the best.

Secondly,
Correct me if I am wrong, but I think you have a typo in data_drop_top_k.py in line 22

    if isinstance(model, str):
        **from train import NormDense**
  
I think it should be:
 
    if isinstance(model, str):
        **from models import NormDense**

Thanks for your GitHub repositories, they are helping me much in my research.

**Comment by leondgarse** [comment]
Ya, you are right! `data_drop_top_k.py` haven't been updated in almost 1 year. Looks like it's me forgot to update while modifying others. :)

**Comment by HamDan1999** [comment]
Noted with thanks!
