### ISSUE TITLE
Resnet101

### ISSUE THREAD

**Issue by 1303463822** [leondgarse/Keras_insightface#107]
resnet.py中Resnet101得模型是不是有问题？Ported Models中r100 12m Adaface权值文件是使用iresnet101训练的嘛？但是在backbones文件夹中并没有看到iresnet模型。

**Comment by leondgarse** [comment]
r100 是用的 resnet.py 中的 resnet100，`resnet.py` 本身的定义是参照 iresnet 来的，比如 [block](https://github.com/leondgarse/Keras_insightface/blob/master/backbones/resnet.py#L60-L74) 中用的是 3x3 卷积，Adaface 中 backbone 模型定义类似：
```py
from backbones import resnet
mm = resnet.ResNet100(input_shape=[112, 112, 3], classes=0, activation='PReLU', use_max_pool=True)
```
这个模型结构跟原本的 `iresnet101` 应该是完全相同的
