### ISSUE TITLE
How to evaluation a h5 model?

### ISSUE THREAD

**Issue by 1303463822** [leondgarse/Keras_insightface#108]
I don't know how to creat a bin file to evaluate and how to prepare a dataset.

**Comment by leondgarse** [comment]
For the typical dataset, you may download them from [insightface/recognition](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_).
For evaluating your own datasets, may follow issues like [How to create bin files for evaluate on training #39](https://github.com/leondgarse/Keras_insightface/issues/39).
