### ISSUE TITLE
How to save the classification head?

### ISSUE THREAD

**Issue by RuoyuChen10** [leondgarse/Keras_insightface#114]
Hi, thanks for your contribution. I want to know how to save the classification head used for identification, what should I operate? Thanks!

**Comment by leondgarse** [comment]
- After training, there will be 2 models being saved, `basic_model` and `model`, and the classifier header for training is saved with `model`, as described in [basic-training](https://github.com/leondgarse/Keras_insightface#basic-training) `Model` part. The `model` is saved as `./checkpoints/{save_path.h5}` and `basic_model` `./checkpoints/{save_path}_basic_agedb30_xxx_epoch_xxx.h5`.
- For running eval or real world recognition, the header is not exists, refer [video_test.py#L90-L105](https://github.com/leondgarse/Keras_insightface/blob/master/video_test.py#L90-L105) for usage.

**Comment by RuoyuChen10** [comment]
> * After training, there will be 2 models being saved, `basic_model` and `model`, and the classifier header for training is saved with `model`, as described in [basic-training](https://github.com/leondgarse/Keras_insightface#basic-training) `Model` part. The `model` is saved as `./checkpoints/{save_path.h5}` and `basic_model` `./checkpoints/{save_path}_basic_agedb30_xxx_epoch_xxx.h5`.
> * For running eval or real world recognition, the header is not exists, refer [video_test.py#L90-L105](https://github.com/leondgarse/Keras_insightface/blob/master/video_test.py#L90-L105) for usage.

Thanks, my problem has been well addressed.
