### ISSUE TITLE
Quantization aware training help

### ISSUE THREAD

**Issue by PR451** [leondgarse/Keras_insightface#115]
Thanks a lot for this awesome repro. 

I have a question regarding quantization aware training. I am new in this area and want to know if you can share example to do quantization aware training for MobileNet or Efficientnet.

**Comment by leondgarse** [comment]
All I learned is from TF tutorial [Quantization aware training in Keras example](https://www.tensorflow.org/model_optimization/guide/quantization/training_example), and it should be easy but not tested. Just adding `quantize_model` after `basic_model` being created should work.
```py
import tensorflow_model_optimization as tfmot
quantize_model = tfmot.quantization.keras.quantize_model
...
from keras_cv_attention_models import efficientnet
basic_model = efficientnet.EfficientNetV2B0(input_shape=(112, 112, 3), num_classes=0)
basic_model = models.buildin_models(basic_model, dropout=0, emb_shape=512, output_layer='GDC', bn_epsilon=1e-4, bn_momentum=0.9, scale=True, use_bias=False)
basic_model = models.add_l2_regularizer_2_model(basic_model, weight_decay=5e-4, apply_to_batch_normal=False)

# q_aware stands for for quantization aware.
basic_model = quantize_model(basic_model)

tt = train.Train(..., basic_model=basic_model, model=None, ...)
...
```
Anyway, quantization not working well for face recognition in my earlier tests. Say a `basic_model` with `256` embedding shape, after quantization, each value can only be `[0, 256]`, means it can be only representing `256 * 256 == 65536` different embeddings, also means only `65536` different faces, which is too small.

**Comment by PR451** [comment]
@leondgarse Thanks a lot. I will give a try.

**Comment by alexandrekj** [comment]
@PR451 you can also try post training quantization when you already have the pre-trained model, in my experience it worked pretty well to reduce model size and obtain better inference times (in my case I obtained a model 3x faster than the non-quantized).


Make sure you have the tensorflow model optimization package:
```
!pip install -q tensorflow-model-optimization
```

And after you have the pre-trained model:

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_quant_model = converter.convert()

# Saving corresponding quantized model
with open('quantized_model.tflite', 'wb') as f:
  f.write(tflite_quant_model)
```

**Comment by leondgarse** [comment]
Ya, just QAT can reach a better accuracy in most cases. If you need the tflite and PTQ data, we have a bunch tests here [How to speed up inference on a quantized model #44](https://github.com/leondgarse/keras_cv_attention_models/discussions/44#discussioncomment-2348910), comparing float16 / uint8 model size and inference speed on x86 / arm using efficientnetv2_s.

**Comment by PR451** [comment]
@leondgarse I tried your above code

`import tensorflow_model_optimization as tfmot
quantize_model = tfmot.quantization.keras.quantize_model
...
basic_model = models.buildin_models("mobilenet", dropout=0.4, emb_shape=512, output_layer='GDC', add_pointwise_conv=True, scale=False, use_bias=True)

# q_aware stands for for quantization aware.
basic_model = quantize_model(basic_model)

tt = train.Train(..., basic_model=basic_model, model=None, ...)`

But I am getting following error 

`RuntimeError: Layer pre_embedding:<class 'keras.layers.normalization.batch_normalization.BatchNormalization'> is not supported. You can quantize this layer by passing a `tfmot.quantization.keras.QuantizeConfig` instance to the `quantize_annotate_layer` API.` I don't know how to quantize the layers using `tfmot.quantization.keras.QuantizeConfig`. 

Have you faced this before?

**Comment by leondgarse** [comment]
Yes, you are right, sorry I didn't take some tests ealier. The reason is that previously appling BatchNormalization on a 2D tensor. Should be fixed now.
```py
import tensorflow as tf
import tensorflow_model_optimization as tfmot
from tensorflow import keras
import models

basic_model = models.buildin_models("mobilenet", dropout=0.4, emb_shape=512, output_layer='GDC', add_pointwise_conv=True, use_bias=True, scale=False, weights=None)
q_aware_model = tfmot.quantization.keras.quantize_model(basic_model)
mm = keras.models.Model(q_aware_model.inputs[0], models.NormDense(10)(q_aware_model.outputs[0]))

xx, yy = tf.random.uniform([1000, 112, 112, 3]), tf.one_hot(tf.random.uniform([1000], 0, 10, dtype='int64'), 10)
mm.compile(optimizer='adam', loss=keras.losses.categorical_crossentropy, metrics=['accuracy'])
mm.fit(xx, yy, epochs=2)
# Epoch 1/2
# 32/32 [==============================] - 31s 198ms/step - loss: 7.1859 - accuracy: 0.1050
# Epoch 2/2
# 32/32 [==============================] - 6s 193ms/step - loss: 7.2841 - accuracy: 0.0930
```

**Comment by PR451** [comment]
@leondgarse Thanks a lot for quick reply. I was able to start the training. Closing the issue.
