### ISSUE TITLE
preprocess_input for Resnet34 on CASIA

### ISSUE THREAD

**Issue by sonfire86** [leondgarse/Keras_insightface#12]
How to find out `preprocess_input` for `Resnet34 on CASIA` ?
https://github.com/keras-team/keras-applications/blob/master/keras_applications/imagenet_utils.py#L152

**Comment by leondgarse** [comment]
I'm not using `preprocess_input` in my code, just read images and preprocessed to `[-1, 1]`

**Comment by sonfire86** [comment]
ok then how is the transformation of the photo going to [-1,1]?

**Comment by leondgarse** [comment]
It's during the dataset preparation [data.py/prepare_dataset](https://github.com/leondgarse/Keras_insightface/blob/dd15db19e1365c0ea4ce204427c33744f13a395c/data.py#L106). Simply `read image` --> `Convert to float` --> `(xx - 127.5) * 0.0078125`, where `0.0078125 == 1 / 128`. This converts `[0, 256]` to `[-1, 1]`.

**Comment by sonfire86** [comment]
But `256 -> 1.00390625`
`(256 - 127.5) * 0.0078125`

**Comment by leondgarse** [comment]
Sorry, it's precisely `[0, 255]` --> `[-0.99609375, 0.99609375]`. I used to use `[0, 255]` --> `((xx / 255) - 0.5) * 2` --> `[-1, 1]`. The `127` way is from the original MXNet version. I'm trying to set every parameter same as MXNet there...

**Comment by sonfire86** [comment]
you used `((xx / 255) - 0.5) * 2` or `(xx - 127.5) * 0.0078125`?These are two different solutions

**Comment by leondgarse** [comment]
Now I'm using `(xx - 127.5) * 0.0078125`, previously it's `((xx / 255) - 0.5) * 2`. It's not a big difference.
