### ISSUE TITLE
Knowledge distillation

### ISSUE THREAD

**Issue by HamadYA** [leondgarse/Keras_insightface#123]
Hi,
Do you have the output of knowledge distillation 'npz' or 'tfrecord' file in a link, please?

$ CUDA_VISIBLE_DEVICES='0' ./data_distiller.py -M subcenter-arcface-logs/r100-arcface-msfdrop75/model,0 -D /datasets/faces_casia_112x112_folders/ -b 32 --use_fp16
Output: faces_casia_112x112_folders_shuffle_label_embs_normed_512.npz

**Comment by leondgarse** [comment]
Sorry but I'm not keeping that either. How about using the ported `h5` models instead of the MXNet one?

**Comment by HamadYA** [comment]
Noted will do
Thanks!
