### ISSUE TITLE
The model classify badly in my test dataset  

### ISSUE THREAD

**Issue by luan1412167** [leondgarse/Keras_insightface#13]
Hi, thanks for your repo, it's useful.
However, I have tested on my test dataset, it gives bad result. Have you tested on IJBB or IJBC or MegaFace?

**Comment by leondgarse** [comment]
Sorry, I havn't test those datasets.
- Which model have you tried? 
- How you calculate the feature? For example, have you prepossessed the image data before feed to model?
```py
img = (img - 127.5) * 0.0078125
```

**Comment by luan1412167** [comment]
@leondgarse yes, I have used your test.py script to test all of models in the checkpoints folder including resnet34 as well.
It looks like the result is worse than insightface model much for comparing on a specified backbone.
Anw, I only want to give you more information. I highly appreciate your works with many useful techniques

**Comment by leondgarse** [comment]
Ya, I'm downloading those two datasets. Thanks for your advise.
Actually I'm also trying to fix a gap between `keras` and `MXnet`. It's the `SGDW` optimizer, their `weight_decay` behaves different. But there should not be big gap if using a same backbone and training dataset...
Speak of my provided `Resnet34`, it is not a good one, as it's only trained on `CASIA` dataset, just aimed to reproduce the paper result...
Any, I will try those datasets later.

**Comment by leondgarse** [comment]
I just done a test on `IJBB` using one of my `mobilenet`. It's not a very good one, but still I think the result is  OK...
Here's the result and plot
```py
Methods     1e-06     1e-05     1e-04     1e-03     1e-02     1e-01
aa       0.288315  0.683934  0.840701  0.921519  0.966991  0.989289
```

![Figure_3](https://user-images.githubusercontent.com/5744524/100612954-bc9fff80-334e-11eb-825f-1bef35e26e71.png)

**Comment by luan1412167** [comment]
@leondgarse thanks for your test. I'm gonna revisit my test code again. It can be my mistake.

**Comment by leondgarse** [comment]
I just uploaded a [IJB_evals.py](https://github.com/leondgarse/Keras_insightface/blob/master/IJB_evals.py) that can be used to test `IJBB / IJBC` dataset using `keras / mxnet` model. You can see the help info for usage, and I'm still writing my readme doc.

For me, I placed the `IJB` dataset `/media/SD/tdtest/IJB_release`, so it's:
```py
# Test mxnet model
CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m '/media/SD/tdtest/IJB_release/pretrained_models/MS1MV2-ResNet100-Arcface/model,0' -L -d /media/SD/tdtest/IJB_release

# Test keras model
CUDA_VISIBLE_DEVICES='1' python IJB_evals.py -m 'checkpoints/basic_model.h5' -L -d /media/SD/tdtest/IJB_release

# Plot result only, this needs the `label` data, which can be saved using `-L` parameter.
# But the mxnet provided `.npy` file not containing it.
# So plot those `npy` can only work with alone at least one of my saved `npz` data.
python IJB_evals.py --plot_only /media/SD/IJB_release/IJBB/result/*100*.npy ../aa.npz
```
|                                           |    1e-06 |    1e-05 |   0.0001 |    0.001 |     0.01 |      0.1 |
|:------------------------------------------|---------:|---------:|---------:|---------:|---------:|---------:|
| MS1MV2-ResNet100-ArcFace-TestMode(N0D0F0) | 0.382765 | 0.893281 | 0.942454 | 0.961538 | 0.975073 | 0.985589 |
| MS1MV2-ResNet100-ArcFace-TestMode(N0D1F0) | 0.389192 | 0.898442 | 0.94557  | 0.96261  | 0.975268 | 0.986076 |
| MS1MV2-ResNet100-ArcFace-TestMode(N0D1F2) | 0.408861 | 0.899513 | 0.946349 | 0.964167 | 0.976144 | 0.98666  |
| MS1MV2-ResNet100-ArcFace-TestMode(N1D0F0) | 0.389971 | 0.904187 | 0.946738 | 0.962025 | 0.976144 | 0.985979 |
| MS1MV2-ResNet100-ArcFace-TestMode(N1D1F0) | 0.392989 | 0.903895 | 0.947614 | 0.962999 | 0.975755 | 0.986076 |
| MS1MV2-ResNet100-ArcFace-TestMode(N1D1F1) | 0.409056 | 0.908082 | 0.947712 | 0.963583 | 0.975463 | 0.986271 |
| MS1MV2-ResNet100-ArcFace-TestMode(N1D1F2) | 0.42814  | 0.908179 | 0.948978 | 0.964654 | 0.976728 | 0.986563 |
| aa                                        | 0.288315 | 0.683934 | 0.840701 | 0.921519 | 0.966991 | 0.989289 |

**Comment by luan1412167** [comment]
thanks for your help, I'm working on it. Your repo is so useful for me. Keep it up

**Comment by luan1412167** [comment]
hi @leondgarse,
I want to test network with IJBB-IJBC but the dataset is not available on DatasetZoo of insightface. Can you share it to me?
Thanks

**Comment by leondgarse** [comment]
Their `Baidu Cloud` link in [recognition/_evaluation_/ijb](https://github.com/deepinsight/insightface/tree/master/recognition/_evaluation_/ijb) still alive, can you download them there? As they are some large files...

**Comment by luan1412167** [comment]
As I am outside it. I can't download it without baidu account. If you can, share to me drive or dropbox link. Big thank to you.

**Comment by leondgarse** [comment]
Then you need to wait my uploading, it takes hours.

**Comment by luan1412167** [comment]
Nice to wait for your uploading. Many thanks

**Comment by leondgarse** [comment]
Google drive links. They are smaller for I removed `result` folders.
- [IJBB.tar.gz](https://drive.google.com/file/d/17--F6lGn6Gzj5u2Dl59fF6KqStvd3jHt/view?usp=sharing)
- [IJBC.tar.gz](https://drive.google.com/file/d/1gwyEbKfL6cY1YsU2IPW8mSS497phNRoH/view?usp=sharing)

**Comment by luan1412167** [comment]
@leondgarse thanks so much for your time. I highly appreciate it.
