### ISSUE TITLE
Face Detector

### ISSUE THREAD

**Issue by yug125lk** [leondgarse/Keras_insightface#135]
Thank you for this great work.
 I'm just a bit confused—are the results with or without face detection? 
When I trained MobileNet with the original dataset, it reached 97.98%. However, when I used the dataset with face detection preprocessing, it only reached 97.45%.

**Comment by leondgarse** [comment]
Sorry for the late reply.
- For training process, the dataset is assumed already handled by face detection. Thus the result is without face detection.
- So the `97.98%` is printed during traing, and `97.45%` is your own testing process result? As the result is rather close, maybe just some difference in image processing like [Reproduce the results #110](https://github.com/leondgarse/Keras_insightface/issues/110), or [flip process](https://github.com/leondgarse/Keras_insightface/blob/master/evals.py#L77-L79)?
