### ISSUE TITLE
license

### ISSUE THREAD

**Issue by serengil** [leondgarse/Keras_insightface#23]
Hello,

Thank you for this amazing work.

InsightFace project has a MIT license and it allows both academic and commercial usage: https://github.com/deepinsight/insightface/blob/master/LICENSE

There is not license info in this keras re-implementation. Please add the license type in both root of the repo and read-me file.

**Comment by leondgarse** [comment]
Thanks, add added. :)

**Comment by serengil** [comment]
Awesome!
