### ISSUE TITLE
How to convert pytorch model to keras and train distill?

### ISSUE THREAD

**Issue by John1231983** [leondgarse/Keras_insightface#26]
Great repo. We found a repo uses pytorch. Could you please add a branch to use pretrained from the repo for keras distillation (similar that you are working on mxnet)?
https://github.com/cavalleria/cavaface.pytorch/blob/master/docs/MODEL_ZOO.md

**Comment by leondgarse** [comment]
Great model zoo, seems some of my planed tests they have already done, like `efficientnet` / `randaug`. :)
I'm not familiar with pytorch model. We only need the inference process to extract the embedding data. So any backend can be used as teacher model. maybe we can try `ONNX`...
