### ISSUE TITLE
train for my own dataset without convert to bin files

### ISSUE THREAD

**Issue by reyhan1994** [leondgarse/Keras_insightface#28]
can I use your repo for my dataset without converting to  .bin or .rec for evaluation? my dataset consists of 200 folders (200person) with 5 images for each person.

**Comment by leondgarse** [comment]
I have uploaded a test file `eval_folder.py` which will do that.
- It will `extract embedding data` --> `pick a representing image from a single class  as registered image` --> `calculate distance between registered images and all others` --> `check if all other images labeled correctly`.
- It also runs `TAR@FAR` test like what we do in `IJB_evals.py`.
- And also a `-D` parameter, if your images are not aligned in `112x112x3` shape already, run this first for face detection. It will save the aligned images in `[data_path] + _aligned_112_112`.
```sh
$ ./eval_folder.py -h
usage: eval_folder.py [-h] -d DATA_PATH [-m MODEL_FILE] [-b BATCH_SIZE] [-D]

optional arguments:
  -h, --help            show this help message and exit
  -d DATA_PATH, --data_path DATA_PATH
                        Data path, containing images in class folders
                        (default: None)
  -m MODEL_FILE, --model_file MODEL_FILE
                        Model file, keras h5 (default: None)
  -b BATCH_SIZE, --batch_size BATCH_SIZE
                        Batch size (default: 64)
  -D, --detection       Run face detection before embedding (default: False)
```
