### ISSUE TITLE
Mobilefacenet

### ISSUE THREAD

**Issue by MayRains** [leondgarse/Keras_insightface#31]
您好，我最近在学习人脸识别的轻量级网络算法（使用keras），请问可以获得您的mobilefacenet的预训练模型么？

**Comment by leondgarse** [comment]
更新在这里了 [current-accuracy](https://github.com/leondgarse/Keras_insightface#current-accuracy)，但只有 `se_mobilefacenet` 的，`mobilefacenet` 的没有训练。

**Comment by MayRains** [comment]
> 更新在这里了 [current-accuracy](https://github.com/leondgarse/Keras_insightface#current-accuracy)，但只有 `se_mobilefacenet` 的，`mobilefacenet` 的没有训练。

👌，谢谢
