### ISSUE TITLE
在test.py文件里，理解不了得到embedding的部分，请求助。

### ISSUE THREAD

**Issue by Shixian520** [leondgarse/Keras_insightface#33]
emb_unk = face_model((nimgs - 127.5) * 0.0078125).numpy()
这是为什么呢？

**Comment by leondgarse** [comment]
输入 `nimgs` 范围 `[0, 255]` --> `nimgs - 127.5) * 0.0078125` 转化到 `[-1, 1]` --> `face_model((nimgs - 127.5) * 0.0078125)` 模型输出特征值。
参考这个 [preprocess_input for Resnet34 on CASIA #12](https://github.com/leondgarse/Keras_insightface/issues/12)

**Comment by Shixian520** [comment]
明白了，还有一个问题。我想把这个代码用在人脸对比，请问怎么能得到threshold？

**Comment by leondgarse** [comment]
cos 距离阈值常用 `0.6`，参照 [Real time face recognition with Android Problem #7](https://github.com/leondgarse/Keras_insightface/issues/7#issuecomment-694732222)

**Comment by Shixian520** [comment]
dist = np.sqrt(np.sum(np.square(np.subtract(face_emb1, face_emb2))))
那这公式是什么意思呢？ 这不是两个特征量之间的距离吗？ 我觉得用这个距离的threshold来判断两个人是否同一个人。

**Comment by leondgarse** [comment]
区别不大，对于归一化后的特征值，欧式距离 `euc_dist = sqrt(2 - 2 * cos_dist)`。对于 `cos` 距离阈值 `> 0.6`，那个公式的欧式距离阈值 `< np.sqrt(0.8)` 判定是否同一个人。
```py
from sklearn.preprocessing import normalize
emb_unk = normalize(emb_unk)

# Use emb_unk[0] as known emb for test
cos_dist = np.dot(emb_unk[0], emb_unk.T)
euc_dist = np.sqrt(((emb_unk[0] - emb_unk) ** 2).sum(1))
print(np.allclose(np.sqrt(2 - 2 * cos_dist), euc_dist))
# True
```

**Comment by Shixian520** [comment]
我想训练自己做的训练集，但不知道每一个人的样本应该为几个？ 20个左右就好了吗？ 另外， 如果得到理想的结果，训练集的大少应该为几个？

**Comment by leondgarse** [comment]
- 制作自己的数据集，首先肯定是越大越好，可以先从 `1000` 个人，每人 `20` 张图片开始，大小没什么定论。
- 完全用自己的数据集用处不大，数据量一般太小了，开源的像是 `glint360k` 有 `360k` 的 id。一般可以先用开源数据集训练，然后在自己数据集上微调 `fine-tune`，参照 [finetune issues from deepinsight/insightface](https://github.com/deepinsight/insightface/issues?q=finetune)。
- Finetune 一般步骤
  - Freeze the early layers in basic_model.
  - Train model using a smaller learning_rate.
  ```py
  import losses, train, models
  # keras.mixed_precision.set_global_policy("mixed_float16")  # May try if float16 can speed up
  
  data_path ='/your_own_dataset_path'
  eval_paths = ['your_own_eval_paths_if_any']
  
  basic_model = keras.models.load_model("your_own_pre_trained_model.h5")  # load the basic_model, inputs --> embeddings
  
  # Freeze layers before "E" / "GDC" / "GAP" head layers.
  # May change the the number `-6` on own needs. See `basic_model.summary()` for layers detail.
  # May also try freeze the whole basic_model by `basic_model.trainable = False` first.
  for ii in basic_model.layers[:-6]:
      ii.trainable = False
  
  # Set a lower learning_rate, like 1e-3
  tt = train.Train(data_path, eval_paths=eval_paths, save_path='new_save_path.h5',
      basic_model=basic_model, model=None, lr_base=1e-3, lr_decay=0.5, lr_decay_steps=16, lr_min=1e-5,
      batch_size=1024, random_status=0, eval_freq=2000, output_weight_decay=1)
  
  optimizer = keras.optimizers.SGD(learning_rate=0.1, momentum=0.9)
  tt.train({"loss": losses.ArcfaceLoss(scale=64), "epoch": 17, "optimizer": optimizer}, 0)
  ```

**Comment by Shixian520** [comment]
谢谢您的指教。 您的详细解说给了我很大的帮助。我还有几个问题继续麻烦大佬。
我了解到百度支持的人脸对比项目会提供两张脸的相似度，比如43%， 76%，就是从0-100之间的数值. 这样的数据怎么可以计算得出？

**Comment by leondgarse** [comment]
百度具体如何定义的百分比不清楚，对于 cos 距离，输出一般为 `[0, 1]`:
- 如果定义输出为 `[0%, 100%]`，可以使用 `cos_dist * 100` --> `0.6 --> 60%`。
- 如果定义输出为 `[50%, 100%]`，可以使用 `(cos_dist / 2 + 0.5) * 100` --> `0.6 --> 80%`。

**Comment by Shixian520** [comment]
训练数据有点小，要用数据增强吗？还有别的更加有效的办法吗？

**Comment by leondgarse** [comment]
可以尝试数据增强，不过人脸数据上 `randaug` 效果似乎不是太好，其他可以尝试的如模型增加 `l2_regularizer` / `dropout`, 或者 optimizer 增加 `weight_decay`:
```py
# Add l2_regularizer
basic_model = models.add_l2_regularizer_2_model(basic_model, weight_decay=5e-4, apply_to_batch_normal=False)
# Or optimizer with weight_decay
optimizer = tfa.optimizers.SGDW(learning_rate=0.1, weight_decay=5e-4, momentum=0.9)
```
其他一些防止过拟合方式如 [Sharpness-Aware Minimization for Efficiently Improving Generalization](https://arxiv.org/pdf/2010.01412.pdf)。
效果有限，增大数据集的效果更明显，比如开源数据集 `CASIA` --> `MS1M` 会有很好的提升。

**Comment by Shixian520** [comment]
我自己做训练数据的时候，如果我不小心把一个人的照片分成两个，也就是说有两个或两个以上的迪丽热巴照片文件夹的话，会不会出现bug？

**Comment by leondgarse** [comment]
应该不会有 bug，这种数据噪声在任何数据集中都可能存在，会影响模型训练的准确度。如果这种数据比较多的话，可以考虑在损失函数中使用 `label_smoothing` [TF CategoricalCrossentropy](https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy)，或者 [sub-center-arcface](https://github.com/leondgarse/Keras_insightface#sub-center-arcface) 先清洗数据。

**Comment by Shixian520** [comment]
每个训练集有两张照片也可以吗？ 我自己做的训练集里大部分只有两张照片，这样的话会不会影响训练结果或者根本就不能训练？

**Comment by leondgarse** [comment]
训练的效果如何呢？2 张确实太少了，这种情况我觉得首先应该扩充数据集

**Comment by Shixian520** [comment]
我是这么做的。利用ImageDataGenerator，对这两张照片进行rotate, horizontal_flip,zoom_range等的操作，把两张照片扩大成20张或以上，但这样做的效果是不是只起到防止过拟合？
另外，我准备了20000组的这样的照片组，也就是说20000 * 2 = 40000张照片。（如果按照上面的操作的话，会扩大成20000 * 20 400000张照片）那我该进行fine-tune呢？ 还是从原先的pretrained模型再训练？

**Comment by leondgarse** [comment]
- 人脸数据是对齐的，也就是五官的位置是调整到了一定位置上的，所以 `rotate` / `zoom_range` 之类的会改变位置的变换方式不是太好。一般添加数据增强是在训练过程中的随机变换，没有确定的数量，参照 [data.py RandomProcessImage](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/data.py#L65)，可以在训练过程中添加颜色 / horizontal_flip 之类的变换。
- 人脸数据集上的数据增强确实效果有限，参照 [cavaface.pytorch Data augmentation](https://github.com/cavalleria/cavaface.pytorch/blob/master/docs/MODEL_ZOO.md#data-augmentation)。所以在常用的开源数据集 `MS1M` 之类的，数据量足够的情况下，一般不添加数据增强了。
- 数据量有限的话，我还是建议从开源数据集训练号的模型开始 fine-tune。

**Comment by Shixian520** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/84282031/119289174-a54a2b00-bc7c-11eb-99f1-aaa385bb63fb.png)
我利用fine-tune进行了20epoch左右, 但是age验证集的accuracy在0.5一点儿也没有变化，我是不是做错了什么？

**Comment by leondgarse** [comment]
是的，这肯定不对，许多方面会导致类似的问题
- 看一下数据预处理的是否正确，有没有转化到 `[-1, 1]`，有没有做人脸对齐
- 损失函数可以先使用 `softmax`
- 学习率设置不能太大

**Comment by Shixian520** [comment]
- 进行了数据预处理，但人脸对齐不知道怎么弄。。

- 您指的是"loss": keras.losses.CategoricalCrossentropy(label_smoothing=0.1), "centerloss": 1, "epoch": 5, "optimizer": optimizer 这样的吗？

- 我吧学习率设置成lr_base=0.001，这算是很小的吧， 然后用了optimizer = tfa.optimizers.AdamW(weight_decay=5e-5). 

大概从25epochage验证集的accuracy慢慢上升，但效果好像不太显著。

**Comment by leondgarse** [comment]
- 人脸对齐可以参照 [eval_folder.py](https://github.com/leondgarse/Keras_insightface/blob/master/eval_folder.py)
  ```py
  import eval_folder
  
  # Single image
  aa = eval_folder.Face_detection()
  nimg = aa.do_detect_in_image('XXXX.jpg')
  print(nimg.shape)
  # (112, 112, 3)
  
  # Pre-process folder
  # IMAGE_FOLDER in form like:
  # .               # dataset folder
  # ├── 0           # person folder
  # │   ├── 100.jpg # face image
  # │   ├── 101.jpg # face image
  # │   └── 102.jpg # face image
  # ├── 1           # person folder
  # │   ├── 111.jpg
  # │   ├── 112.jpg
  # │   └── 113.jpg
  eval_folder.detection_in_folder('IMAGE_FOLDER')
  ```
- 可以尝试 `keras.losses.CategoricalCrossentropy()`，先不使用 `label_smoothing`，`centerloss` 不是太好。
- 可以尝试 `optimizer="adam"`，先不使用 `weight_decay`。
- `thresh` 值正常应该会 `< 0.3`，表示区分正反例的 cosine 距离阈值，`> 0.99` 的话基本算是没法使用。。

**Comment by Shixian520** [comment]
![Screenshot_7](https://user-images.githubusercontent.com/84282031/119424497-274b5a00-bd38-11eb-8c7c-38725ead35e4.png)
![Screenshot_8](https://user-images.githubusercontent.com/84282031/119424503-2adee100-bd38-11eb-9a90-8025e4e19f33.png)
NormDense是什么意思呢？ 然后最终得到的.h5文件里有两个输出，一个是embedding，另一个是通过NormDense的arcface, 怎样能得到embedding?

**Comment by leondgarse** [comment]
- 上一个截屏里，模型的保存两个
  - `keras_efficientnet_emoreIII.h5` 是带 `NormDense` 层的模型，用于模型训练
  - `keras_efficientnet_emoreIII_basic_agedb_30_epoch_xxx.h5` 是输出 `embedding` 的模型，用于部署
- README 中有说明，Model contains two part
  - **Basic model** is layers from input to `embedding`.
  - **Model** is `Basic model` + `bottleneck` layer, like `softmax` / `arcface` layer. For `triplet` training, `Model` == `Basic model`. For combined `loss` training, it may have multiple outputs.
- 你这个有两个输出，看起来是用了 `arcface + centerloss / triplet` 输出的模型吧

**Comment by Shixian520** [comment]
明白了，但是如果我要读取keras_efficientnet_emoreIII.h5在继续进行模型训练，会出现上面的错误。就是Unknown layer:NormDense，我试了custom_objects属性，但不行。
为什么我要用keras_efficientnet_emoreIII.h5呢，是因为微调的时候第一个epoch的eval_accuracy很高，但显然这时模型还没训练我自己的数据集，然后这样的话后面的eval_accuracy都比第一个epoch低，不能得到他们的keras_efficientnet_emoreIII_basic_agedb_30_epoch_xxx.h5这样的模型。
所以我想先训练10个epoch左右，得到keras_efficientnet_emoreIII.h5，然后读取他以后继续训练，这样可以得到eval_accuracy较高，而且充分训练的模型。
我是不是太low了。。

**Comment by leondgarse** [comment]
- 如果是加载模型继续训练，可以在初始化 `train.Train` 的时候指定
  ```py
  tt = train.Train(data_path, save_path, eval_paths,
      basic_model=None, model='./checkpoints/keras_efficientnet_emoreIII.h5',  # Full path of loaded model
      ...)
  ```
  `train.Train` 里会自己处理 `custom_objects.update({"NormDense": models.NormDense})`
- 直接加载模型通过指定 `custom_objects` 也应该是可以的
  ```py
  import models
  model = tf.keras.models.load_model('./checkpoints/keras_efficientnet_emoreIII.h5', compile=False,
              custom_objects={"NormDense": models.NormDense})
  ```
  加载模型后可以自己保存 `basic_model`
  ```py
  basic_model = tf.keras.models.Model(model.inputs[0], model.layers[-2].output)  # Embedding output layer
  basic_model.save('aa.h5')
  ```
- 训练结束后也可以自己保存 `basic_model`
  ```py
  tt.basic_model.save('aa.h5')
  ```
- 具体训练的效果的话，我也不知道了

**Comment by Shixian520** [comment]
我想每个epoch都输出模型，而输出模型的名字里包含loss的值，该怎么改callback?

**Comment by leondgarse** [comment]
- 如果是保存 `model`，临时加一下的话可以放到 [my_callbacks.py My_history](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/myCallbacks.py#L61) 里，这里获取 `loss` 比较方便
  ```py
  # Add from line 62
  loss = self.history["loss"][-1]
  save_name = self.initial_file.split("_hist.json")[0] + "_epoch_{}_loss_{}.h5".format(epoch, loss)
  self.model.save(save_name)
  ```
- 如果是保存 `basic_model`，可以放到 [evals.py eval_callback](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/evals.py#L126) 里，将下面这部分
  ```py
  if acc_max >= self.max_accuracy:
      tf.print(">>>> Improved = %f" % (acc_max - self.max_accuracy))
      self.max_accuracy = acc_max
      if self.save_model:
          save_name_base = "%s_basic_%s_epoch_" % (self.save_model, self.test_names)
          save_path_base = os.path.join("./checkpoints", save_name_base)
          for ii in glob2.glob(save_path_base + "*.h5"):
              os.remove(ii)
          save_path = save_path_base + "%s_%f.h5" % (cur_step, self.max_accuracy)
          tf.print("Saving model to: %s" % (save_path))
          self.basic_model.save(save_path, include_optimizer=False)
  ```
  改成
  ```py
  tf.print(">>>> Improved = %f" % (acc_max - self.max_accuracy))
  self.max_accuracy = acc_max
  if self.save_model:
      save_name_base = "%s_basic_%s_epoch_" % (self.save_model, self.test_names)
      save_path_base = os.path.join("./checkpoints", save_name_base)
      save_path = save_path_base + "%s_%f.h5" % (cur_step, self.max_accuracy)
      tf.print("Saving model to: %s" % (save_path))
      self.basic_model.save(save_path, include_optimizer=False)
  ```

**Comment by Shixian520** [comment]
谢谢。
另外，我想用我自己做的数据集进行验证，也就是说每个epoch后，不用agedb_30.bin等文件，想用自己做的文件夹，要用eval_folder.py吗？ 但具体用法有点儿搞不明白。
还有，如果我要制作agedb_30.bin一样的文件，该怎么做？

**Comment by leondgarse** [comment]
- `eval_folder.py` 参照 [issue #28](https://github.com/leondgarse/Keras_insightface/issues/28)，这个基本是为了在训练结束后在私有数据集上验证模型效果，每个 epoch 用的话需要自己封装成 `callback`，在 `on_epoch_end` 调用，参照 `evals.py`。
- 创建 `bin` 参照 [issues #32](https://github.com/leondgarse/Keras_insightface/issues/32)，对于验证数据集文件夹结构
  ```sh
  .              # dataset folder
  ├── 1          # person folder
  │   ├── 10.jpg # face image
  │   ├── 11.jpg # face image
  │   └── 12.jpg # face image
  ├── 2          # person folder
  │   ├── 20.jpg # face image
  │   ├── 21.jpg # face image
  │   └── 22.jpg # face image
  ```
  选取 `image_list` 与 `is_same_list`，表示两个图片是否是同一个人，如选取
  ```sh
  #    image_list   | is_same_list
  1/10.jpg 1/11.jpg | 1
  2/10.jpg 2/21.jpg | 1
  1/12.jpg 2/22.jpg | 0
  1/10.jpg 2/10.jpg | 0
  ```
  参照 [prepare_data.py MXnet_bin_files_to_tf](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/prepare_data.py#L38) 创建 `bin`
  ```py
  # Selected image_list and is_same_list
  image_list = ["1/10.jpg", "1/11.jpg", "2/10.jpg", "2/21.jpg", "1/12.jpg", "2/22.jpg", "1/10.jpg", "2/10.jpg"]
  is_same_list = [1, 1, 0, 0]
  
  # Save to bin
  import pickle
  from skimage.io import imread
  
  bb = [tf.image.encode_jpeg(imread(ii)).numpy() for ii in image_list]
  with open("aa.bin", "wb") as ff:
      pickle.dump([bb, is_same_list], ff)
  ```
  测试
  ```py
  import evals
  mm = keras.models.load_model("basic_model.h5")
  ee = evals.eval_callback(mm, 'aa.bin')
  ee.on_epoch_end()
  ```

**Comment by Shixian520** [comment]
我自己做了bin数据，我加了5000组True和1000组False, 但evaluating过程中有bug。
![Screenshot_9](https://user-images.githubusercontent.com/84282031/119583790-eb78c900-bdf9-11eb-869e-c2ac29c0f6fe.png)

**Comment by Shixian520** [comment]
我用debug测试过，发现agedb_30的 n_same, n_diff的值一直为2700，然后变成300，这是什么意思呢？

**Comment by leondgarse** [comment]
- `PCA_acc` 的计算过程比较麻烦，对于 `agedb_30` `is_same_list` 中 `True` 的数量为 `3000`
  - [evals.py#L223](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/evals.py#L223) 这里 `actual_issame[train_set]` 对应 `n_same == 2700`，表示 `90%` 的 `True` 样。
  - [evals.py#L230](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/evals.py#L230) 这里 `actual_issame[test_set]` 对应 `n_same == 300`，表示 `10%` 的 `True` 样本。
- 如果需要计算 `PCA_acc`，验证数据集的制作需要按照它的计算方式来。。就是 `[10% True, 10% False, 10% True, %10 False, ...]` 这样，如果有 20 个 True，10 个 False 的话 `is_same_list` 就是 `[1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0]`，否则会像上面那样报错。
- 如果不是必要的话，可以先把 `eval_callback` 的 `PCA_acc` 关掉 `PCA_acc=False`，`eval_callback` 里的另一种 accuracy 计算方式 `acc_count = np.array([(tt > vv).sum() + (ff <= vv).sum() for vv in ff[-t_steps:]])` 不需要改变 `is_same_list`。

**Comment by Shixian520** [comment]
已解决， 我制作bin文件的时候，进行了shuffle，避免了上面的错误发生。
**evaluation max accuracy: 0.999833**, thresh: 0.459912, previous max accuracy: 0.000000, PCA accuray = 0.982500 ┬▒ 0.004787
这里evaluation max accuracy为99.98%是不是错误的？ 怎么可能这么高？

**Comment by leondgarse** [comment]
- 这个准确率应该是 6000 个样本里只错了一个，确实有点太高了，可能是因为选取的验证样本都是简单好区分的样本，或者训练数据集跟验证数据集比较接近。
- 可以把 [evals.py#L104](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/evals.py#L104) 这一行注释打开，保存一下中间计算结果，其中 `tt` / `ff` 分别表示所有正例 / 负例样本 cosine 相似度，然后看一下分布，如果确实区分很好的话，那就是数据集的问题了。
  ```py
  import evals
  mm = keras.models.load_model("basic_model.h5")
  ee = evals.eval_callback(mm, 'aa.bin')
  ee.on_epoch_end()
  
  import matplotlib.pyplot as plt
  plt.hist(ee.ff, bins=512, density=True, alpha=0.5, label="negative")
  plt.hist(ee.tt, bins=512, density=True, alpha=0.5, label="positive")
  plt.legend()
  plt.show()
  ```
  ![pos_neg_hist](https://user-images.githubusercontent.com/5744524/119616522-47ac0f00-be33-11eb-8286-06dc1ee88765.png)

**Comment by Shixian520** [comment]
![Screenshot_14](https://user-images.githubusercontent.com/84282031/119640603-5c949c80-be4b-11eb-80e2-dc0a60b5dc51.png)
这里的evaluation max accuracy为150%...正负资料的比例为1:1，各为1000张。。。我很困惑。

**Comment by leondgarse** [comment]
这个确实比较奇怪，而且这个数量也太整齐了，看起来似乎只测了几个，能把你的 bin 文件发给我吗？通过 Google / Baidu 网盘之类的

**Comment by Shixian520** [comment]
https://we.tl/t-tdCy4pN1Z9
这是wetransfer文件，能不能帮我看一下

**Comment by leondgarse** [comment]
是我的错，`is_same_list` 里应该是 `bool` 类型。。按照下面转化一下就好了
```py
import pickle
import numpy as np

bb, is_same_list = np.load('zip.bin', encoding="bytes", allow_pickle=True)
is_same_list = np.array(is_same_list).astype('bool').tolist()
with open("zip2.bin", "wb") as ff:
    pickle.dump([bb, is_same_list], ff)
```
测试结果
```py
>>>> zip2 evaluation max accuracy: 0.972500, thresh: 0.192555, previous max accuracy: 0.000000, PCA accuray = 0.969000 ± 0.005385
```

**Comment by Shixian520** [comment]
TAR@FAR=1e-4是什么意思呢？ TAR和FAR值越小越好吗？
然后我一直有疑问，就是EfficientNet和ResNet之间，到底哪一个更好呢？

**Comment by leondgarse** [comment]
- TAR@FAR=1e-4 表示在 FAR = 1e-4 时的 TAR 值，一般是此时的 TAR 值越大越好，对于 TAR - FAR 的 ROC 图可以使用 `IJB_evals` 中的函数简单绘制，在得到 `ee.tt` 与 `ee.ff` 之后：
  ```py
  from IJB_evals import plot_roc_and_calculate_tpr
  
  score = np.hstack([ee.tt, ee.ff])
  label = [1] * ee.tt.shape[0] + [0] * ee.ff.shape[0]
  plot_roc_and_calculate_tpr(scores=[score], names=['agedb_30'], label=label)
  ```
  ![far_tar](https://user-images.githubusercontent.com/5744524/119805345-bfea0180-bf13-11eb-9bee-581a8148cce0.png)
- 按照发表的论文的话，EfficientNet / EfficientNetV2 都是要比 ResNet 更好，但我觉得也关系到具体的训练参数 / 策略 / 数据集之类的，比如我使用跟 resnet 同样的参数训练 `EfficientNetV2_S` / `EfficientNetV2_M`，结果就很不好。。

**Comment by Shixian520** [comment]
![Screenshot_16](https://user-images.githubusercontent.com/84282031/119936783-46f2b480-bfbc-11eb-933a-d87d3f14df80.png)

训练代码中加"triplet": 64利用Batch Hard Triplet Loss， 但出现上面的Error，以前没有的...

**Comment by leondgarse** [comment]
不应该啊，到达报错那里的时候，`image_dataframe` 应该是经过 `groupby --> apply`，是个 `Series` 才对。过程就是下面这样
```py
import data
data_path = 'faces_emore_test'

image_names, image_classes, embeddings, classes, _ = data.pre_process_folder(data_path, data.default_image_names_reg, data.default_image_classes_rule)
image_dataframe = pd.DataFrame({"image_names": image_names, "image_classes": image_classes})
print(type(image_dataframe))
# pandas.core.frame.DataFrame

image_dataframe = image_dataframe.groupby("image_classes").apply(lambda xx: xx.image_names.values)
print(type(image_dataframe))
# pandas.core.series.Series

image_per_class = 4
split_func = lambda xx: np.array(np.split(np.random.permutation(xx)[: len(xx) // image_per_class * image_per_class], len(xx) // image_per_class))

shuffle_dataset = image_dataframe.map(split_func)
```

**Comment by Shixian520** [comment]
客户需要我们模型的FAR，FRR值。我了解到FAR，FRR值的基本含义，但要得到它们的具体值，是不是需要一个特定的数据集来计算？
另外，可以留大神的邮箱吗？在GitHub提问，有点儿麻烦。

**Comment by leondgarse** [comment]
是的，需要基于某个数据集，论文中常用 [IJBB / IJBC](https://github.com/leondgarse/Keras_insightface#evaluating-on-ijb-datasets) 以及 Megaface。
邮箱 leondgarse@gmail.com，你点我头像，主页那里就有。。

**Comment by Shixian520** [comment]
![Screenshot_36](https://user-images.githubusercontent.com/84282031/121320009-5a4c3b00-c93f-11eb-94bd-52e39927a602.png)
走几个epoch,就会出现这样的错误，不知道是什么原因。
然后不知道我的电脑是不是在使用GPU，这是不是不运行GPU？
![Screenshot_37](https://user-images.githubusercontent.com/84282031/121321784-fd518480-c940-11eb-9bcb-7eb6101baaa5.png)

**Comment by leondgarse** [comment]
- 这个错误没遇到过，看起来是 [loss.py L75](https://github.com/leondgarse/Keras_insightface/blob/cb2912491a718246f392497a7c396f81d1d592c5/losses.py#L75) `theta_one_hot = tf.expand_dims(theta_valid - y_pred_vals, 1) * tf.cast(y_true, dtype=tf.float32)` 这里，`y_true` 的 shape 是 `[512, 163740]`，`theta_valid - y_pred_vals` 的 shape 是 `[520]`。在 [losses.py L62](https://github.com/leondgarse/Keras_insightface/blob/cb2912491a718246f392497a7c396f81d1d592c5/losses.py#L62) 后面加一个打印和断言看看，其中的 `512` 是你的 `batch_size`：
  ```py
  tf.print(", y_true.sum:", tf.reduce_sum(y_true), ", y_pred_vals.shape:", K.shape(y_pred_vals), end="")
  tf.assert_equal(tf.reduce_sum(y_true), 512)
  tf.assert_equal(K.shape(y_pred_vals)[0], 512)
  ```
  我也想不出来什么情况会这样，可能 `y_true` 里面某一个 one_hot 值里面有多个 `1`？可是这不应该发生。
- 如果改变过数据集里面的结构，可以删除项目目录下的缓存文件 `[dataset_name]_112x112_folders_shuffle.npz` 试试。
- 训练过程中使用 `nvidia-smi` 查看，我的 GPU 使用率一般是 `100%`。可以看一下在 `import tensorflow as tf` 的时候是否有报错，或者在 import 之后查看当前的 GPU 信息
  ```py
  tf.config.experimental.list_physical_devices("GPU")
  # [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
  ```
  都没有问题的话，有可能是数据读取上有瓶颈，看一下训练开始的前几个 batch 后有没有警告信息。

**Comment by leondgarse** [comment]
如果上面那个问题还是存在的话，可以尝试在 `ArcfaceLoss` 中保存一下 `y_true` `norm_logits`，出错的时候再具体查看一下
- `loss.py ArcfaceLoss` 的 `__init__` 函数中添加
  ```py
  self.norm_logits = tf.Variable(tf.zeros([512, 163740]), dtype="float32", trainable=False)
  self.y_true = tf.Variable(tf.zeros([512, 163740], dtype="int32"), dtype="int32", trainable=False)
  ```
  其中 `[512, 163740]` 是 `[batch_size, classes]`
- `loss.py ArcfaceLoss` 的 `call` 函数中在一开始添加
  ```py
  self.norm_logits.assign(norm_logits)
  self.y_true.assign(y_true)
  ```
- `data.py` 中所有的 `ds = ds.batch` 中添加参数 `drop_remainder=True`
- `data.py` 中所有的 `steps_per_epoch = int(np.ceil(` 改为 `steps_per_epoch = int(np.floor(`

**Comment by whalefa1I** [comment]
感谢，我感觉在看论语
