### ISSUE TITLE
ValueError: Cannot assign to variable Variable:0 due to variable shape (5568, 512) and value shape (86688, 512) are incompatible.

### ISSUE THREAD

**Issue by Shixian520** [leondgarse/Keras_insightface#34]
这错误是什么意思呢？

**Comment by leondgarse** [comment]
在加载模型的时候类别数量不匹配？

**Comment by Shixian520** [comment]
已解决。

**Comment by Shixian520** [comment]
![Screenshot_5](https://user-images.githubusercontent.com/84282031/119329413-c4b27980-bcb7-11eb-8b94-4815fec14b53.png)

这是什么原因呢？

**Comment by leondgarse** [comment]
看起来是 `gently_stop` 报的错，我没有在 windows 上测试过，之前这里没有报错吗？
解决方法的话可以关闭 `gently_stop`
```py
# Add before tt.train(sch, 0)
tt.gently_stop = None
```

**Comment by Shixian520** [comment]
多谢大佬指点。 如果我想达到您这样的水平，该看什么书，该做什么呢？

**Comment by leondgarse** [comment]
我也还差得远，许多问题都是在实际使用中遇到，慢慢学习的，教程的话基本只是看 TF 官方的 [tutorials](https://www.tensorflow.org/tutorials) 和 [guide](https://www.tensorflow.org/guide)。

**Comment by Shixian520** [comment]
- 我想用欧拉距离 dist = np.sqrt(np.sum(np.square(np.subtract(face_emb1, face_emb2))))来代替您用的cos距离，请问，我该在哪儿改代码？
- 然后“alpha float value, default to 0.35. Alpha value for BatchHardTripletLoss if attached.“。 是不是alpha值越大越好啊？
- 我们要开发一个人脸对比系统，所以会发现模型会把很多不同人的组合视为同一个人，这种情况下我该怎么改进模型？ 把他们两个人的数据分别加到训练集在训练吗？但他们的照片都各有一张，想加到训练集比较麻烦。

**Comment by Shixian520** [comment]
- 我想用欧拉距离 dist = np.sqrt(np.sum(np.square(np.subtract(face_emb1, face_emb2))))来代替您用的cos距离，请问，我该在哪儿改代码？
- 然后“alpha float value, default to 0.35. Alpha value for BatchHardTripletLoss if attached.“。 是不是alpha值越大越好啊？
- 我们要开发一个人脸对比系统，所以会发现模型会把很多不同人的组合视为同一个人，这种情况下我该怎么改进模型，解决这种个例？ 把他们两个人的数据分别加到训练集再训练吗？但他们的照片都各有一张，想加到训练集比较麻烦。

**Comment by leondgarse** [comment]
- 你是指 `evals.py` 里的距离计算吗？但像之前解释过的，这样不会有什么影响，两种距离计算没什么本质区别。以下这些没有测试，大体应该是这样
  ```py
  # evals.py line 100
  - dists = (embs_a * embs_b).sum(1)
  + dists = np.sqrt(((embs_a - embs_b) ** 2).sum(1))
  
  # evals.py line 107
  - acc_count = np.array([(tt > vv).sum() + (ff <= vv).sum() for vv in ff[-t_steps:]])
  + acc_count = np.array([(tt < vv).sum() + (ff >= vv).sum() for vv in ff[t_steps:]])
  ```
  `video_test.py` 里的话就是 [video_test.py#L98](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/video_test.py#L98)
  ```py
  # video_test.py line 98
  - dists = np.dot(embeddings, emb_unk.T).T
  - rec_idx = dists.argmax(-1)
  + dists = np.array([np.sqrt(((embeddings - ii) ** 2).sum()) for ii in emb_unk])
  + rec_idx = dists.argmin(-1)
  ```
- alpha 值不是越大越好，alpha 越小相当于越关注更难的训练样本，具体多少合适还得自己调试。triplet 问题在于虽然会提高验证集上的准确度，但是会缩小正负样本之间的分割区间 `margin`，也就是之前绘制的那个分布图中，negative 与 positive 的分布会靠的更近。
- 只有一张也可以给每个人创建单独的分类合并到数据集中，但这样可能只是对这一个特例有所帮助，整体上这样的问题还是需要提高模型精度，用更大的模型，更大的训练数据集之类的。其次可以看一下这种特例的分割阈值，提高判定成同一个人的阈值。

**Comment by Shixian520** [comment]
![Screenshot_15](https://user-images.githubusercontent.com/84282031/119766383-7edbf800-bee7-11eb-8966-cdde4cd811d5.png)
这是age_db的欧拉距离，计算得到的阈值是1.348150，但从histogram可以看到阈值在1.3左右。

**Comment by leondgarse** [comment]
重新来一下，这样
```py
# evals.py line 100
- dists = (embs_a * embs_b).sum(1)
+ dists = np.sqrt(((embs_a - embs_b) ** 2).sum(1))

# evals.py line 107
- acc_count = np.array([(tt > vv).sum() + (ff <= vv).sum() for vv in ff[-t_steps:]])
+ acc_count = np.array([(tt < vv).sum() + (ff >= vv).sum() for vv in ff[:t_steps]])

# evals.py line 110
- self.acc_thresh = ff[acc_max_indx - t_steps]
+ self.acc_thresh = ff[acc_max_indx]
```

**Comment by Shixian520** [comment]
谢谢，完美解决

**Comment by Shixian520** [comment]
我给您的邮箱发了个邮件，能帮我看一下吗，谢谢

**Comment by Shixian520** [comment]
我给您的邮箱发了个邮件，您看到了吗？

**Comment by leondgarse** [comment]
昨天下午已经回复了啊，是个 outlook.com 的邮箱，是没收到吗？看一下有没有在垃圾邮件里？你的邮件包括 5.16 的邮件都是因为被过滤掉了，所以没看到。。我重新发到了你的 163 邮箱

**Comment by Shixian520** [comment]
不是...那个邮件呢我收到了，然后昨天我还发了一个，您没收到吗? 我还重新发了一下。
________________________________

**Comment by Shixian520** [comment]
屡次冒犯，真不好意思
________________________________

**Comment by leondgarse** [comment]
不不不，没看到邮件确实是我的问题。。

**Comment by laym99** [comment]
> 已解决。

请问是如何解决的？

**Comment by leondgarse** [comment]
@KlayCurry1130 遇到的具体是什么问题呢？这个错误大概可能是 load_weights 的时候定义的 num_classes 不一致。有具体 log 的话你可以单独开一个 issue

**Comment by adjlaj** [comment]
> 

你好！你怎么解决的呢

**Comment by leondgarse** [comment]
@adjlaj  遇到的具体是什么问题呢？这个错误大概可能是 load_weights 的时候定义的 num_classes 不一致。有具体 log 的话你可以单独开一个 issue
