### ISSUE TITLE
训练时间很长，是否正常？

### ISSUE THREAD

**Issue by yafengwa** [leondgarse/Keras_insightface#37]
单卡RTX2080TI
数据：DeepGlint (181K ids/6.75M images)
网络：Mobilenet

一个轮回要十多个小时

**Comment by leondgarse** [comment]
不正常，我们也用 RTX2080T，MS1MV3 (93K ids/5.1M images) 上一个 epoch ~35分钟。我没有 DeepGlint 数据集，应该也不至于十几个小时
- 看一下 GPU 有没有用起来
- 可以尝试 float16 `keras.mixed_precision.set_global_policy("mixed_float16")`

![Selection_367](https://user-images.githubusercontent.com/5744524/120745698-4b751b00-c530-11eb-94ab-c45dc1780e80.png)

**Comment by yafengwa** [comment]
> 不正常，我们也用 RTX2080TI，MS1MV3 (93K ids/5.1M images) 上一个 epoch ~35分钟。我没有 DeepGlint 数据集，应该也不至于十几个小时
> 
> * 看一下 GPU 有没有用起来
> * 可以尝试 float16 `keras.mixed_precision.set_global_policy("mixed_float16")`
> 
> ![Selection_367](https://user-images.githubusercontent.com/5744524/120745698-4b751b00-c530-11eb-94ab-c45dc1780e80.png)

非常感谢，可以分享一下你环境的版本吗，包括对应的cuda.

**Comment by leondgarse** [comment]
- 大概环境参考 [Readme environment](https://github.com/leondgarse/Keras_insightface#environment)
- 目前具体版本
  - `cuda-driver` 11.2.152-1
  - `libcudnn8` 8.1.1.33-1+cuda11.2
  - `nvidia-driver-465` 465.19.01-0ubuntu1
 - 只要是 `TF` / `cuda` / `cudnn` 相互匹配的版本差别并不大

**Comment by Shixian520** [comment]
你好，MS1MV3的下载地址能共享一下吗？

**Comment by leondgarse** [comment]
就是 [insightface/Dataset-Zoo](https://github.com/deepinsight/insightface/wiki/Dataset-Zoo#ms1m-retinaface) 里的 `ms1m-retinaface`

**Comment by yafengwa** [comment]
数据缩减到了三百多万，ids 八万多，环境已升级到最新，系统win10和ubantu也都试过，时间还是很慢，我感觉我买了假显卡【笑哭】
![2](https://user-images.githubusercontent.com/38486610/122346482-94d75880-cf7b-11eb-96c6-36bd07f4f4f9.jpg)
![1](https://user-images.githubusercontent.com/38486610/122346508-9dc82a00-cf7b-11eb-8ea4-614b8e2976de.jpg)
非常困扰。。。。

**Comment by leondgarse** [comment]
- 看一下在不使用 `mixed_float16` 的情况下，速度是比这快还是慢，TF 在某些显卡，某些训练参数下 float16 可能会更慢 [Conv2D is 20x slower using mixed_float16 in training process](https://github.com/tensorflow/tensorflow/issues/48127)。
- 跑一些简单的代码试试
  ```py
  import tensorflow as tf
  from tensorflow import keras
  
  gpus = tf.config.experimental.list_physical_devices("GPU")
  for gpu in gpus:
      tf.config.experimental.set_memory_growth(gpu, True)
  
  keras.mixed_precision.set_global_policy("mixed_float16")

  def load_cifar10(batch_size=1024, image_shape=(32, 32)):
      import tensorflow_datasets as tfds
      AUTOTUNE = tf.data.experimental.AUTOTUNE
  
      if image_shape[:2] == (32, 32):
          preprocessing = lambda data: (tf.cast(data["image"], tf.float32) / 255.0, data["label"])
      else:
          preprocessing = lambda data: (tf.image.resize(data["image"], image_shape[:2]) / 255.0, data["label"])
          # preprocessing = lambda data: (tf.transpose(tf.image.resize(data["image"], image_shape[1:]) / 255.0, [2, 0, 1]), data["label"])
      dataset = tfds.load("cifar10", split="train").map(preprocessing, num_parallel_calls=AUTOTUNE)
      dataset = dataset.cache().batch(batch_size).prefetch(buffer_size=AUTOTUNE)
      return dataset
  
  dataset = load_cifar10(batch_size=512, image_shape=(112, 112))
  model = keras.applications.MobileNet(input_shape=(112, 112, 3), classes=10, weights=None)
  optimizer = keras.optimizers.Adam()
  model.compile(loss='sparse_categorical_crossentropy', optimizer=optimizer)
  history = model.fit(dataset, epochs=5)
  ```
  我的 `RTX 2080 Ti` 上的结果
  | mixed_float16 | batch_size | total time (5 epochs) | mean         |
  | ------------- | ---------- | --------------------- | ------------ |
  | False         | 320        | 192 s                 | 38.4 s/epoch |
  | True          | 512        | 85 s                  | 17 s/epoch   |
  
  作为对比，colab 上 `Tesla T4` 的结果
  | backbone  | mixed_float16 | batch_size | total time (5 epochs) | mean          |
  | --------- | ------------- | ---------- | --------------------- | ------------- |
  | MobileNet | False         | 512        | 361 s                 | 72.2 s/epoch  |
  | MobileNet | True          | 512        | 170 s                 | 34 s/epoch    |
  | ResNet50  | False         | 512        | 753 s                 | 150.6 s/epoch |
  | ResNet50  | True          | 512        | 368 s                 | 73.6 s/epoch  |

**Comment by yafengwa** [comment]
非常感谢，不同得参数会影响一些速度，但是不大。
我可能找到原因了，我把数据缩减至2.6M/60K ids 速度貌似恢复正常仅15分钟，我猜测是我电脑得磁盘有问题，磁盘读写速率低时GPU利用率也非常低。
![3](https://user-images.githubusercontent.com/38486610/122492748-ec77d180-d018-11eb-96bf-1aa99e6152ca.jpg)
