### ISSUE TITLE
Ablation Studies for different activations/architecture?

### ISSUE THREAD

**Issue by vizakshat** [leondgarse/Keras_insightface#38]
Not an issue just a suggestion. BTW I think this is a very good repo.

And I found some pre-trained models on the first page {README}. I think the pre-trained models are heavily independent of each other in terms of the last layer (GDC vs E), training data (Emore vs MSMv3), activation functions (Swish vs PRelu), and architectures (many!).

I think it will be good. If someone can provide some ablation studies on these as it's very hard to isolate the variables which perform better.

**Comment by leondgarse** [comment]
Speaking of those perfomance, in my practice, seems E > GDC, Swish > PReLU > ReLU, MSMv3 > Emore. I'm just picking my best ones to publish in readme.
I'm actually collecting my own training data, like this Mobilenet one, but it's getting hard to align data like this... Just so many options...

![Mobilenet](https://user-images.githubusercontent.com/5744524/120758353-4f129d00-c544-11eb-8e05-a0b0f55e3c34.png)
