### ISSUE TITLE
How to create bin files for evaluate on training

### ISSUE THREAD

**Issue by malik-anhar** [leondgarse/Keras_insightface#39]
I want to train the model using my own dataset and instead of using lfw and some other datasets for evaluate the model while training, I want to use my own evaluation data. So how can we create the .bin file? Thanks in advance

**Comment by leondgarse** [comment]
- Refer to [issues #32](https://github.com/leondgarse/Keras_insightface/issues/32). For validating data folder in format:
  ```sh
  .              # dataset folder
  ├── 1          # person folder
  │   ├── 10.jpg # face image
  │   ├── 11.jpg # face image
  │   └── 12.jpg # face image
  ├── 2          # person folder
  │   ├── 20.jpg # face image
  │   ├── 21.jpg # face image
  │   └── 22.jpg # face image
  ```
  Pick your own `image_list` and `is_same_list`, representing if they are a same person or not:
  ```sh
  #    image_list   | is_same_list
  1/10.jpg 1/11.jpg | True
  2/20.jpg 2/21.jpg | True
  1/12.jpg 2/22.jpg | False
  1/10.jpg 2/20.jpg | False
  ```
  Refer to [prepare_data.py MXnet_bin_files_to_tf](https://github.com/leondgarse/Keras_insightface/blob/9eb7ad39960f21905bb80a4810c0e200b0723301/prepare_data.py#L38) creating your own `bin`:
  ```py
  # Selected image_list and is_same_list
  image_list = ["1/10.jpg", "1/11.jpg", "2/20.jpg", "2/21.jpg", "1/12.jpg", "2/22.jpg", "1/10.jpg", "2/20.jpg"]
  is_same_list = [True, True, False, False]
  
  # Save to bin
  import pickle
  from skimage.io import imread
  
  bb = [tf.image.encode_jpeg(imread(ii)).numpy() for ii in image_list]
  with open("aa.bin", "wb") as ff:
      pickle.dump([bb, is_same_list], ff)
  ```
  Test
  ```py
  import evals
  mm = keras.models.load_model("basic_model.h5")
  ee = evals.eval_callback(mm, 'aa.bin')
  ee.on_epoch_end()
  ```

**Comment by leondgarse** [comment]
I just updated my `eval_folder.py`. Now it can generate bin test file by `-B save_bins`:
```sh
CUDA_VISIBLE_DEVICES='1' ./eval_folder.py -m basic_odel.h5 -d temp_test/faces_emore_test -B temp_test/foo.bin
```
The main part is [generate_eval_pair_bin](https://github.com/leondgarse/Keras_insightface/blob/a368930cf4a2be3b45131ba1537db4d1daccc99c/eval_folder.py#L184). Its pos / neg pairs picking strategy is not the best one, but just works.
