### ISSUE TITLE
Train with own dataset on Resnet34

### ISSUE THREAD

**Issue by zul96a** [leondgarse/Keras_insightface#43]
Hello Sir! I found your repo to be very helpful and useful.

I'm planning to train a model with my own dataset which consist of person images (mostly selfies) and their ID photos, so currently I'm doing some data cleaning and preparation.
My question is, is face detector included in this repo? Or do I have to crop and extract the face from the ID photos?

Thanks again!

**Comment by leondgarse** [comment]
Yes, you have to crop and extract the face from the ID photos before training.
You can use `Face_detection` from my `eval_folder.py`. It will download and init a face detector from `insightface`.
```sh
pip install insightface
```
```py
from eval_folder import Face_detection
dd = Face_detection()  # Init a detector

# Test image
from skimage.data import astronaut
img = astronaut()
bbs, ccs, pps, nimg = dd.detect_in_image(img)

# bbs is the bbox, ccs is the confidence, pps is the key points, nimg is the aligned face images.
print(bbs.shape, ccs.shape, pps.shape, nimg.shape)
# (1, 4) (1,) (1, 5, 2) (1, 112, 112, 3)

plt.imshow(nimg[0])

dd.show_result(img, bbs, ccs, pps)
```
`dd.detect_in_folder` will do detection in folder and save results to `{DATASET}_aligned_112_112`
```py
dd.detect_in_folder(dataset_folder)
```
