### ISSUE TITLE
how can I solve this example error

### ISSUE THREAD

**Issue by RFTFT** [leondgarse/Keras_insightface#46]
![Screenshot from 2021-08-30 21-44-08](https://user-images.githubusercontent.com/33363102/131348960-e9177fe7-37a4-4081-9d55-e5914b605000.png)

![Screenshot from 2021-08-30 21-42-09](https://user-images.githubusercontent.com/33363102/131348855-ec317ce2-0d6b-4a07-a1bb-f8a73c5b62fe.png)

**Comment by leondgarse** [comment]
It seems like complaining your `dataset_params` is `None`, you can print it out to say what happens to it. That error line should be [train.py#L157](https://github.com/leondgarse/Keras_insightface/blob/498aed550bcb927f1c64b955dc3fa31605a5ed27/train.py#L157). maybe you changed something?

**Comment by RFTFT** [comment]
Thank you, I find that ichanged something make this error

**Comment by leondgarse** [comment]
I've tested on colab, and it should work fine:
![Selection_400](https://user-images.githubusercontent.com/5744524/131767180-09a64345-a44c-499c-a937-46f1c25831b3.png)

Also, I changed `centerloss` calculation from `reduce_mean` to `reduce_sum` long ago, means it's enlarged by multiply with `batch_size`. So should use something like `"centerloss: 0.01"` `"centerloss: 0.1"`.

**Comment by RFTFT** [comment]
[image: Screenshot from 2021-09-04 18-10-51.png]
This is my code

**Comment by RFTFT** [comment]
This is my error log and I print dataset_params
![Screenshot from 2021-09-04 18-14-15](https://user-images.githubusercontent.com/33363102/132091039-e55257d0-4d85-4e4e-b4b9-6a42e8ebfcb9.png)

**Comment by leondgarse** [comment]
I think it's `data.prepare_dataset` returned `None`. I just added more log info in this process.
This could happen if your `data_path` directory is not exists, or it's empty.
Besides, may also remove the cache file `[data_path]_shuffle.npz` to try again.

**Comment by RFTFT** [comment]
Thank you for your help
I found that my datasets folder name was different
