### ISSUE TITLE
关于预训练模型的结果

### ISSUE THREAD

**Issue by whalefa1I** [leondgarse/Keras_insightface#47]
使用[预训练模型](https://drive.google.com/file/d/1Mb2ZjBHFSQha8y2UOXO6-vxNWdzw815P/view)进行finetune，在前几个epoch都是0.5，应该很正常，但是我用以下代码看了看自己生成的bin的结果，发现有些奇怪
我用的代码：
```
from  tensorflow.keras as keras
import evals
import matplotlib.pyplot as plt

bin_path = '我自己的bin'
model_path = '下载的预训练模型'
mm = keras.model.load_model(model_path)
ee = evals.eval_callback(mm,  bin_path )

plt.hist(ee.ff, bins=512, densitu=True, alpha=0.5,label='neg')
plt.hist(ee.tt, bins=512, densitu=True, alpha=0.5,label='pos')
plt.legend()
plt.show()
```
我获得的结果图片
![image](https://user-images.githubusercontent.com/32239722/134796878-a65de768-1fca-4e04-b2fe-c5da623e5a7b.png)
看上面的图片我获得了正反导致的结果图像，是哪里有问题吗？[bin](https://drive.google.com/file/d/1eOtwBLpjA2i0c9osNQIsBRcaUa_88fxM/view?usp=sharing)

**Comment by whalefa1I** [comment]
有这个的话，那我在我的数据集上反向操作一下不是能获得很好的效果吗

**Comment by leondgarse** [comment]
可能是 bin 的问题？上面代码看起来没有问题，不应该这样。bin 文件的链接打不开，似乎共享的时候不是公开的？

**Comment by whalefa1I** [comment]
https://drive.google.com/file/d/1eOtwBLpjA2i0c9osNQIsBRcaUa_88fxM/view?usp=drivesdk

**Comment by whalefa1I** [comment]
您看看上面那个可以吗

**Comment by leondgarse** [comment]
可以，下完了，可以取消了

**Comment by leondgarse** [comment]
你 positive 里的图没对齐啊，很多是横向的，negative 里也有横向的和上下颠倒的

**Comment by whalefa1I** [comment]
其实是mtcnn对齐过的，但是原图如果是颠倒的对齐出来有可能也是颠倒的

**Comment by whalefa1I** [comment]
(怎么通过embedding返回成图片的...

**Comment by leondgarse** [comment]
直接从 bin 文件里读取就可以了
```py
bins, issame_list = np.load(test_bin_file, encoding="bytes", allow_pickle=True)
aa = np.stack([tf.image.decode_image(ii, channels=3) for ii in bins])

plt.imshow(np.hstack(aa[:10]))
```

**Comment by whalefa1I** [comment]
....我以为是个不可逆的embedding呢！！！

**Comment by whalefa1I** [comment]
开始很多0.5是因为你用neg的后0.1去分割的所以最好的都是0.5, 啊现在有点心累啊，看样子我没法分出来了

**Comment by leondgarse** [comment]
一般第一个 epoch 后还是 0.5 的话，基本算是训练失败了，可以看看是哪里的问题，调整下重新开始了。

**Comment by whalefa1I** [comment]
带有embeddings的npz文件可以还原成图片吗？

**Comment by whalefa1I** [comment]
看起来都是归一化的数组

**Comment by leondgarse** [comment]
上面 bin 文件是因为里面本来就是保存的 png / jpg 格式的图片，只是从里面将图片读取出来，没有从 embedding 还原成图片的方法。

**Comment by whalefa1I** [comment]
哦哦我看到bin是怎么做的了，就是decode了一下（这个bin麻烦删一下谢谢嘻嘻）

**Comment by leondgarse** [comment]
好的，删了
