### ISSUE TITLE
KeyError: 'input_1_ib-0' , memory allocation error

### ISSUE THREAD

**Issue by zul96a** [leondgarse/Keras_insightface#48]
Hi there again!
I got an error when initiating the training, it gives me this output.

![image](https://user-images.githubusercontent.com/77947380/135193319-9165d92f-14c2-4595-9d0a-5b00833ed1ce.png)

These are my codes : 
![image](https://user-images.githubusercontent.com/77947380/135193400-5a126bdf-8e4c-44a0-97f1-b79b41e1a146.png)

I suspect this has to do something with tensorflow clashing with keras but I'm not sure. Thanks!

**Comment by leondgarse** [comment]
I saw your files date is 2 months ago, and I do have a commit about 1 months ago to [fit TF 2.6.0](https://github.com/leondgarse/Keras_insightface/commit/ad81c00a1e2f35db9ccbcdb674b7f455400583c5#diff-dcfeaa5ac3dffd54264034760914588d92fc7395c81eaa9274715840dc28100b). Maybe you are using `TF 2.6.0` and didn't get this updated? The key change there is like:
```py
- from tensorflow.python.keras import layers
+ from tensorflow.keras import layers
```

**Comment by zul96a** [comment]
Thanks for the quick reply! Yeah, the update does fix my problem. Thanks again!!

**Comment by zul96a** [comment]
Hello again! Sorry but I have another issue (and I don't want to open a new thread because might be too many threads) , regarding memory exhaustion. The codes are same as above and here is the details of total images and classes 
![image](https://user-images.githubusercontent.com/77947380/135208865-3de838a5-134f-4a4f-a3a2-0c71e90863de.png)

I'm using my own dataset (around 15k images + CASIA webface) for training and the face_emore as evaluation. My server details are
![image](https://user-images.githubusercontent.com/77947380/135208977-77369c8b-2c91-49e7-8f62-fa50d1b5969d.png)

And I got the error message "tensorflow.python.framework.errors_impl.ResourceExhaustedError: failed to allocate memory [Op:Mul]".
I tried to lower the batch size until 16 and include mixed_precision, but I still get the memory throwback. Do you have any suggestion on what I can do?

**Comment by leondgarse** [comment]
In the log, you got 6573531 classes... By default it's using person folder names as classes at [data.py#10](https://github.com/leondgarse/Keras_insightface/blob/faa8bce5e0da59bf40b392ca714ebc616072df4b/data.py#L10):
```py
default_image_classes_rule = lambda path: int(os.path.basename(os.path.dirname(path)))
```
The largest folder name will by used as total classes. If your folder name is not numerical increasing class names, may try change [data.py#48](https://github.com/leondgarse/Keras_insightface/blob/faa8bce5e0da59bf40b392ca714ebc616072df4b/data.py#L48):
```py
- image_classes_rule = default_image_classes_rule
+ image_classes_rule = ImageClassesRule_map(data_path)
```

**Comment by leondgarse** [comment]
OK, I just updated using `ImageClassesRule_map` as default behavior... You can remove the backuped cache `[data_path]_shuffle.npz` and try again.

**Comment by zul96a** [comment]
Thanks! I pulled the latest code and it works now! The classes number has changed 
![image](https://user-images.githubusercontent.com/77947380/135215220-790ef0d9-9665-472e-ad96-5de6cb9b7c0d.png)
The machine still gives memory throwback but i fixed it buy lowering the batch size to 128 

But I'm a bit worried since the classes should be around 15k based on the aligned_112 dataset 
![image](https://user-images.githubusercontent.com/77947380/135215442-f6b72670-09a6-41e0-bb0e-224cad04efba.png)
So I'll have to check it out why the number isn't the same.

The reason why I choose Resnet34 is due one of the face verification framework that I'm using  (https://github.com/serengil/deepface) uses your keras implementation and I checked it was resnet34 as base model.
Thank you again sir for your help and I'm making sure to include credits for this repo!

**Comment by zul96a** [comment]
Hello. I'm just wondering if png image format is applicable for training. I'm having concern due to custom data (4k person) that I added to CASIA webface is likely not included since read total class was 10575, which should be 15k. Thanks.

**Comment by whalefa1I** [comment]
> Hello. I'm just wondering if png image format is applicable for training. I'm having concern due to custom data (4k person) that I added to CASIA webface is likely not included since read total class was 10575, which should be 15k. Thanks.

You can refer to: data.py line 9 for more details

**Comment by leondgarse** [comment]
As currently it's using `ImageClassesRule_map` as default rule, not concerning it's `png` / `jpg`. So technically total classes should be same with:
```py
import glob2
data_path = /datasets/faces_casia_112x112_folders/'
print(len(glob2.glob(os.path.join(data_path, '*'))))
# 10572

data_path = /datasets/ms1m-retinaface-t1_112x112_folders/'
print(len(glob2.glob(os.path.join(data_path, '*'))))
# 93431
```
For CASIA dataset, it's `10572`, just `3` from yours. Not sure why skipped some in your dataset. Can you check it with `glob`?
And @whalefa1I , I just changed the default rule, thus data.py L9 is not using now. :)

**Comment by leondgarse** [comment]
Sorry, png is excluded, and data.py L9 still works..
`png` should also work, you may try changing data.py L9:
```py
- default_image_names_reg = os.path.join("*", "*.jpg")
+ default_image_names_reg = os.path.join("*", "*")
```

**Comment by leondgarse** [comment]
Sorry, just excited off work, I'll do some tests...

**Comment by zul96a** [comment]
noted with thanks! Please take your time.

**Comment by leondgarse** [comment]
Just updated default `image_names_reg` rule, you may try again. In my tests, [data.py#L60](https://github.com/leondgarse/Keras_insightface/blob/29080ebbf30ece580b8e2c4e0815c214a6862cd2/data.py#L60) `tf.image.decode_jpeg` also works with `png` images, but `tf.image.decode_image` throws some error, so I'm keeping `tf.image.decode_jpeg` there.

**Comment by whalefa1I** [comment]
> Just updated default `image_names_reg` rule, you may try again. In my tests, [data.py#L60](https://github.com/leondgarse/Keras_insightface/blob/29080ebbf30ece580b8e2c4e0815c214a6862cd2/data.py#L60) `tf.image.decode_jpeg` also works with `png` images, but `tf.image.decode_image` throws some error, so I'm keeping `tf.image.decode_jpeg` there.

Sometime it throws error since the size of image is 0

**Comment by zul96a** [comment]
Noted with thanks!
