### ISSUE TITLE
Distributed training

### ISSUE THREAD

**Issue by abdikaiym01** [leondgarse/Keras_insightface#52]
Is your code ready to use distributed training on many gpus?

**Comment by leondgarse** [comment]
I tested it under 2 GPUs, just wrapper the model building and training process under `with tf.distribute.MirroredStrategy().scope():`, like my description here [Multi GPU train using horovod or distribute strategy](https://github.com/leondgarse/Keras_insightface#multi-gpu-train-using-horovod-or-distribute-strategy).
