### ISSUE TITLE
Preprocessing image 

### ISSUE THREAD

**Issue by abdikaiym01** [leondgarse/Keras_insightface#54]
In order to match two faces is it enough to apply this transformation (image - 127.5) * 0.0078125. The preprocessing image stage will be correct?

**Comment by leondgarse** [comment]
Ya, processing image to `[-1, 1]` is enough. Like `(image - 127.5) * 0.0078125` for image `[0, 255]`, `image * 2 - 1` for image `[0, 1]`.
