### ISSUE TITLE
Validation on your open source models

### ISSUE THREAD

**Issue by abdikaiym01** [leondgarse/Keras_insightface#55]
I tested your model and get bad results on my own validation dataset. Why is that happend? I send validation resluts on your email (leondgarse@gmail.com). Could you explain why that happend, although your model show good accuracy on open source validation data-sets?

**Comment by leondgarse** [comment]
I still haven't received your mail yet. Technically, Just following the steps `face detection in image` --> `face align` --> `normalize to [-1, 1]` --> `input to model and get embedding output` --> `l2 normalize embedding` --> `calculate cosine distance` is enough. Processes in my [video_test.py](https://github.com/leondgarse/Keras_insightface/blob/master/video_test.py) is following this. You can also refer to my [Colab efficientnetV2_basic_test.ipynb](https://colab.research.google.com/drive/1vmAEfF9tUgK2gkrS5qVftadTyUcX343D?usp=sharing#scrollTo=VV5ZTpg5sTLT) `Keras insightface test` section.
We are actually using some of these models in our production environment, and the performance so far so good. :)

**Comment by abdikaiym01** [comment]
I found my problem. That happened because of not correctness of align process. Thank you!)

**Comment by leondgarse** [comment]
OK, I can also close this then. :)
