### ISSUE TITLE
Training stop at Epoch 1

### ISSUE THREAD

**Issue by malik-anhar** [leondgarse/Keras_insightface#58]
Hi, I have been experimenting with Keras Insightface to train using our images and happen to cross an error.
The training exit without any errors or warnings at epoch 1. Is there any missing parameters?

Thank you.

![image](https://user-images.githubusercontent.com/72056043/146347241-f605f071-c88c-4354-acd5-255a2bc20356.png)

**Comment by leondgarse** [comment]
It seems your dataset is too small, only 47 images and 48 classes? I guess it's because the total images is smaller than your batch_size.
What's your dataset be like?

**Comment by malik-anhar** [comment]
Hmm, I see, I have also tried with full datasets than other error happens. 
![image](https://user-images.githubusercontent.com/72056043/146473477-e7adf20c-b1b6-4254-bdb5-0e1db60f78e3.png)

Actually, I want to try to train for 88 people (88 folders) with 5 pictures samples for each person. Each picture is sized around 257 x 257 pixels. Would there be any recommendation for the hyperparameters?
![image](https://user-images.githubusercontent.com/72056043/146473726-6bbc9aed-2790-4451-b3a9-469a182f1c4d.png)

**Comment by leondgarse** [comment]
69003071 classes with 264 images? That single matrix `[256, 69003071]` will need 65G GPU memory. I think that's not right. It's your dataset in the format like the description in [my README](https://github.com/leondgarse/Keras_insightface#beforehand-data-prepare)?

**Comment by leondgarse** [comment]
Uh, I think you are using a very early version of my repo, right? Because many log info not matching with my current version... Maybe you can try the latest one, especially the `data.py`. The `ImageClassesRule_map` using there may solve your classes problem.

**Comment by malik-anhar** [comment]
I am doing already the exact same steps as in the README just to get an overview of how the things work.

The datasets is using **faces_emore_112x112_folders** generated via prepare_data.py, but when I try to train using the example script, this error come out "ValueError: Can't convert non-rectangular Python sequence to Tensor."
![image](https://user-images.githubusercontent.com/72056043/146531976-1462eb0d-39a7-4cf8-945b-c2731c35be5e.png)

This is the training script I use
![image](https://user-images.githubusercontent.com/72056043/146531686-9d5ad88f-10da-4b88-bb1e-bdfbd1197ef2.png)

Anything that I need to adjust? If this works, I will try to adjust my datasets according to this face_emore one. Thanks.

**Comment by leondgarse** [comment]
- I don't know if it's intended to be, but you are using both `\` with `/` in your paths? Shouldn't it be all `\` for windows? The error is threw from `evals.py` that its `bins` cannot be converted to tensor.
- I think that error `ValueError: Can't convert non-rectangular Python sequence to Tensor` is the same one told in [my README beforehand-data-prepare](https://github.com/leondgarse/Keras_insightface#beforehand-data-prepare). Maybe you didn't get your `.bins` converted using `-T` param?

**Comment by malik-anhar** [comment]
Ahh yes, my mistakes, thanks for pointing it out. I have re-tried to convert using `-T` and it seems to work a bit. 
Unfortunately, the datasets is not loaded, I believe. 
It stated `[Error] total_images is 0, image_names: [] image_classes: []` while in the actual data_path, the images are exists (around 85000+ folders).
![image](https://user-images.githubusercontent.com/72056043/146567515-a84c5c78-02c6-4764-bc3f-285d8ef46391.png)
![image](https://user-images.githubusercontent.com/72056043/146567622-72513cda-094f-4d76-958d-f1f5f9d5831b.png)

**Comment by leondgarse** [comment]
The only thing I can tell from this log, you may remove the cache file `dfaces_emore_112x112_folders_shuffle.npz` and run again. If still encounter this error, may check your `data_path` param, it just cannot find any folder there. There are others running their training on Windows, It should work there.

**Comment by malik-anhar** [comment]
Hi again, I am changing the environment to linux now due to data_path you have mentioned, I think in Windows there is some special char that I need further explore.
And in linux, it seems to work fine but the training always exit, are there anything wrongly put in for the parameters?
![image](https://user-images.githubusercontent.com/72056043/146726697-4098fe45-070c-448b-ae83-9c80b55c171c.png)

**Comment by leondgarse** [comment]
I cannot tell from this one. You may add more log after each`self.__init_xxx__` step in `train.py` to see which one blocking it. Actually seldom do I saw it exits without any error info. Firstly make sure `__init_dataset__` finished its job, then it maybe somewhere in `__init_optimizer__`.

**Comment by malik-anhar** [comment]
Hi, I have somehow manage to run all the training, thankfully.
Thanks for the help :)

Just one more questions, regarding the evaluating bin files. Is it generated automatically or I need to create .txt file containing the pair images in our datasets?
![image](https://user-images.githubusercontent.com/72056043/147023763-5cbd7da1-721b-47da-aca2-9687283a2ee2.png)

**Comment by leondgarse** [comment]
Congrats! You don't need the `txt` file. The basic structure is simple, needs two parts `images` and `is_same_list`:
  ```py
  image_list = [
      "1/10.jpg", "1/11.jpg",
      "2/20.jpg", "2/21.jpg",
      "1/12.jpg", "2/22.jpg",
      "1/10.jpg", "2/20.jpg"
  ]
  is_same_list = [True, True, False, False]
  
  # Save to bin
  import pickle
  from skimage.io import imread
  
  bb = [tf.image.encode_jpeg(imread(ii)).numpy() for ii in image_list]
  with open("aa.bin", "wb") as ff:
      pickle.dump([bb, is_same_list], ff)
  ```
You can also refer to [my generate_eval_pair_bin](https://github.com/leondgarse/Keras_insightface/blob/d21cde9a4b497b3107ca2d32b666f61271afcd40/eval_folder.py#L183). First step is picking pairs by distance. The final saving items is `bins` and `issame_list`.

**Comment by malik-anhar** [comment]
Okay thanks again.. Keep contributing @leondgarse and educate other :)
