### ISSUE TITLE
help

### ISSUE THREAD

**Issue by nadongjin** [leondgarse/Keras_insightface#59]
I ask you for help.
There is always only 1 epoch running.
From the second epoch, an error occurs.
The error is:

=================================error========================================
Saving model to: checkpoints\20211222_resnet152v_basic_agedb_30_epoch_1_0.668667.h5
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
C:\Users\facetag\Face_project\venv\lib\site-packages\keras\utils\generic_utils.py:497: CustomMaskWarning: Custom mask layers require a config and must override get_config. When loading, the custom mask layer must be passed to the custom_objects argument.
  category=CustomMaskWarning)

Epoch 00001: saving model to checkpoints\20211222_resnet152v.h5

Traceback (most recent call last):
  File "C:/Users/facetag/Face_project/my_insight/real_train.py", line 35, in <module>
    tt.train(sch, 0)
  File "C:\Users\facetag\Face_project\my_insight\train.py", line 452, in train
    self.train_single_scheduler(**sch, initial_epoch=initial_epoch)
  File "C:\Users\facetag\Face_project\my_insight\train.py", line 435, in train_single_scheduler
    self.__basic_train__(initial_epoch + epoch, initial_epoch=initial_epoch)
  File "C:\Users\facetag\Face_project\my_insight\train.py", line 344, in __basic_train__
    workers=4,
  File "C:\Users\facetag\Face_project\venv\lib\site-packages\keras\engine\training.py", line 1230, in fit
Continue? ([Y]/n):     callbacks.on_epoch_end(epoch, epoch_logs)
  File "C:\Users\facetag\Face_project\venv\lib\site-packages\keras\callbacks.py", line 413, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "C:\Users\facetag\Face_project\my_insight\myCallbacks.py", line 19, in on_epoch_end
    if not self.yes_or_no():
  File "C:\Users\facetag\Face_project\my_insight\myCallbacks.py", line 15, in <lambda>
    self.yes_or_no = lambda: "n" not in self.timeout_input(prompt, time_out, default="y")[1].lower()
  File "C:\Users\facetag\Face_project\my_insight\myCallbacks.py", line 24, in timeout_input
    inputs, outputs, errors = select.select([sys.stdin], [], [], timeout)
=========================================================================
=====================================================================
import models
from backbones import resnet
import train,losses
import tensorflow_addons as tfa
import tensorflow as tf

data_path = 'D:/new_dataset/faces_emore_112x112_folders'
eval_paths = ['D:/new_dataset/faces_emore/lfw.bin', 'D:/new_dataset/faces_emore/cfp_fp.bin', 'D:/new_dataset/faces_emore/agedb_30.bin']

# strategy = tf.distribute.MirroredStrategy(devices=["/gpu:0", "/gpu:1"], cross_device_ops=tf.distribute .HierarchicalCopyAllReduce())

#basic_model=models.buildin_models(resnet.ResNet100(input_shape=(112,112,3),activation='PReLU',classes=0,pooling=None),emb_shape=512, output_layer="E",,bn_momentum=0.9,bn_epsilon=1e-5)

tf.keras.mixed_precision.set_global_policy("mixed_float16")

with tf.distribute.MirroredStrategy(devices=["/gpu:0", "/gpu:1"],cross_device_ops=tf.distribute .HierarchicalCopyAllReduce()).scope():
    basic_model = models.buildin_models(
        resnet.ResNet152(input_shape=(112, 112, 3), activation='PReLU', classes=0, pooling=None),
        emb_shape=512, output_layer="E", bn_momentum=0.9, bn_epsilon=1e-5, dropout=0, pointwise_conv_act="prelu")

    tt = train.Train(data_path, save_path='20211222_resnet152v.h5', eval_paths=eval_paths,
                    basic_model=basic_model, batch_size=256, random_status=0,
                    lr_base=0.1, lr_decay=0.1, lr_decay_steps=[3, 5, 7, 16, 20, 24])

    optimizer = tfa.optimizers.SGDW(learning_rate=0.1, weight_decay=5e-4, momentum=0.9)
    sch = [
      {"loss": losses.ArcfaceLoss(scale=16), "epoch": 5, "optimizer": optimizer}
      # {"loss": losses.ArcfaceLoss(scale=32), "epoch": 5},
      # {"loss": losses.ArcfaceLoss(scale=64), "epoch": 40}
      # {"loss": losses.ArcfaceLoss(), "epoch": 20, "triplet": 64, "alpha": 0.35},
    ]
    tt.train(sch, 0)
==========================================================================

**Comment by leondgarse** [comment]
I changed `self.gently_stop = None`. Maybe it's not working well on Windows. You may try again.

**Comment by nadongjin** [comment]
> I changed `self.gently_stop = None`. Maybe it's not working well on Windows. You may try again.

Thank you so much for your quick reply.
