### ISSUE TITLE
Parameters ArcLoss

### ISSUE THREAD

**Issue by sonfire86** [leondgarse/Keras_insightface#6]
What parameters used for ArcLoss? `s = ?, m = ?`

**Comment by leondgarse** [comment]
I'm using the default one , `margin1=1.0, margin2=0.5, margin3=0.0, scale=64.0`, means `s = 64, m = 0.5`,

**Comment by sonfire86** [comment]
@leondgarse 
For any datasets?

**Comment by leondgarse** [comment]
I just tested them on `emore` and `casia` dataset. These are the recommended parameters in the original `insightface`, and there are also other combinations. like
```py
# [margin1, margin2, margin3]
"W&F Norm Softmax": [1, 0, 0],
"SphereFace": [1.5, 0, 0],
"CosineFace": [1, 0, 0.35],
"ArcFace": [1, 0.5, 0],
"Combined Margin_1": [1.2, 0.4, 0],
"Combined Margin_2": [1.1, 0, 0.35],
"Combined Margin_3": [1, 0.3, 0.2],
"Combined Margin_4": [0.9, 0.4, 0.15],
```
`Scale` is usually `64`.

**Comment by sonfire86** [comment]
thnx
