### ISSUE TITLE
yolov5s_face_dynamic.h5的臉部landmark怎麼取得？

### ISSUE THREAD

**Issue by c7934597** [leondgarse/Keras_insightface#70]
請問關於yolov5s_face_dynamic.h5的臉部landmark怎麼取得？以下有幾個問題詢問：

1.我先理一下流程，你是用"純臉部的圖片"資料集與yolov5s，訓練出一個臉部偵測的物件偵測功能，然後再用YoloV5FaceDetector，帶入DEFAULT_ANCHORS與DEFAULT_STRIDE找到landmark嗎？還是你的臉部資料集，本身資料集不是純臉部，而是有landmark的資料集了？

2.如果是臉部偵測資料集且有landmark，請問可以分享資料集嗎？我也想學著用yolo來訓練自己的臉部landmark偵測版本，謝謝你。

3.因為看起來像landmark是後面算出來的，想請問YoloV5FaceDetector細節，我這方面比較不懂，請見諒，是否有參考文章教學抓到臉後計算出landmark的方式？因為單純看你這段程式碼我不知道為什麼要這樣做，主要是因為我目前情境需要用C翻寫這段。

4.以下這兩個參數為什麼數值要帶這樣，anchors這個是你用yolo時，訓練設定的anchor嗎？不過我記得不是大概6或9個整數的數字嗎？
DEFAULT_ANCHORS = np.array(
    [
        [[0.5, 0.625], [1.0, 1.25], [1.625, 2.0]],
        [[1.4375, 1.8125], [2.6875, 3.4375], [4.5625, 6.5625]],
        [[4.5625, 6.781199932098389], [7.218800067901611, 9.375], [10.468999862670898, 13.531000137329102]],
    ],
    dtype="float32",
)
DEFAULT_STRIDES = np.array([8, 16, 32], dtype="float32")

**Comment by leondgarse** [comment]
- 模型来自 [deepcam-cn/yolov5-face](https://github.com/deepcam-cn/yolov5-face)，训练数据集是 `WIDERFace datasets`，具体训练部分参照那边 Pytorch 的。我的模型是从 Pytorch 那边转化过来的，转化部分来自 [Github ultralytics/yolov5](https://github.com/ultralytics/yolov5.git)。`YoloV5FaceDetector` 只是封装了前后的数据处理，刚刚添加了来源链接。
- landmarks 计算我也是从 Pytorch 移植过来的，要跑训练的话还是要参照那边的。
- 具体的 `anchors` / `strides` 是在转化过程中输出的值，我这里直接复制过来用了。

**Comment by c7934597** [comment]
感謝分享與解答，謝謝。
