### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor

### ISSUE THREAD

**Issue by malik-anhar** [leondgarse/Keras_insightface#75]
Hi,
I would like to ask whether anyone ever have the same issue like me.
The error show after training is done and the model is generated and saved.
Is there any particular mistake in file naming or due to other issues?
![image](https://user-images.githubusercontent.com/72056043/150900092-2d88fe4b-ce1f-43dd-99e1-bd266d3cd008.png)

Thanks.

**Comment by leondgarse** [comment]
Never happened for me. It should be all done except some print work when that log `DONE!!!` printed. Idk what's wrong after that,maybe some tensorflow error? as it's related with `multiprocessing`.

**Comment by leondgarse** [comment]
Feel free to reopen this if your issue still exist. Closing now.
