### ISSUE TITLE
Hard coded values in video_test.py

### ISSUE THREAD

**Issue by shounakshastri** [leondgarse/Keras_insightface#89]
Hello,

I was going through the code and I couldn't make it out what these values are in the `video_test.py` file. 

```
def face_align_landmarks_sk(img, landmarks, image_size=(112, 112), method="similar"):
    tform = transform.AffineTransform() if method == "affine" else transform.SimilarityTransform()
    src = np.array([[38.2946, 51.6963], [73.5318, 51.5014], [56.0252, 71.7366], [41.5493, 92.3655], [70.729904, 92.2041]], dtype=np.float32)
```
and 

`        nimgs = (np.array(nimgs) - 127.5) * 0.0078125`

How are these numbers derived? Thank you.

**Comment by leondgarse** [comment]
- `src = np.array([[38.2946, 51.6963], [73.5318, 51.5014], [56.0252, 71.7366], [41.5493, 92.3655], [70.729904, 92.2041]], dtype=np.float32)` is point where a typical face `left_eye, right_eye, nose, mouse_left, mouse_right` located in a `112 x 112` image.   Detected face key points are aligned to these points.
  ```py
  src = np.array([[38.2946, 51.6963], [73.5318, 51.5014], [56.0252, 71.7366], [41.5493, 92.3655], [70.729904, 92.2041]], dtype=np.float32)
  aa = np.ones([112, 112, 3])
  plt.imshow(aa)
  plt.scatter(src[:, 0], src[:, 1])
  ```
  ![face_src_points](https://user-images.githubusercontent.com/5744524/167074704-6de4dad4-d4f2-48c5-a323-087d10c6c845.png)
- `nimgs = (np.array(nimgs) - 127.5) * 0.0078125` is rescaling image in `[0, 255]` to `[-1, 1]`, where `0.0078125 == 1 / 128`. Several ways can be applied for this aim:
  ```py
  img = (img - 128) / 128
  # Or
  img = img / 128 - 1
  ```
  Not a big difference.

**Comment by shounakshastri** [comment]
Ah ok!
Thank you!
