### ISSUE TITLE
Restore training from Mobilenet

### ISSUE THREAD

**Issue by DonkeySmall** [leondgarse/Keras_insightface#93]
Hello, i want to restore training from Mobilenet emb256, Emore,E110 model, where can i find the weight?

**Comment by leondgarse** [comment]
- If you mean my pretrained weights, it's the link in first column in readme model table: [Mobilenet emb256](https://drive.google.com/file/d/1i0B6Hy1clGgfeOYtUXVPNveDEe2DTIBa/view?usp=sharing). This is the `basic_model` only.
- If restore from your own training break point, follow `Restore training from break point` in [README basic-training](https://github.com/leondgarse/Keras_insightface#basic-training). Basically, your own trained model is under `[training_path]/checkpoints/`.

**Comment by DonkeySmall** [comment]
I try to continue training from your [Mobilenet emb256](https://drive.google.com/file/d/1i0B6Hy1clGgfeOYtUXVPNveDEe2DTIBa/view?usp=sharing) pretrained weight but getting error `AttributeError: 'Train' object has no attribute 'triplet'`

```
import losses, train, models
import tensorflow_addons as tfa

data_path = 'E:\\datasets\\faces_emore\\faces_emore_112x112_folders'
eval_paths = ['E:\\datasets\\faces_emore\\faces_emore\\lfw.bin', 'E:\\datasets\\faces_emore\\faces_emore\\cfp_fp.bin', 'E:\\datasets\\faces_emore\\faces_emore\\agedb_30.bin']

tt = train.Train(data_path, save_path='E:\\datasets\\faces_emore\\checkpoints\\mobilerestore.h5', eval_paths=eval_paths,
    basic_model=None, model="E:\\datasets\\faces_emore\\checkpoints\\mobilerestore.h5",
    lr_base=0.0001, lr_decay=0.1, lr_decay_steps=[90, 100], batch_size=48, random_status=0)
optimizer = tfa.optimizers.SGDW(learning_rate=0.0001, weight_decay=5e-6, momentum=0.9)

tt.train_single_scheduler(loss=losses.ArcfaceLoss(scale=64), epoch=30, optimizer=optimizer, initial_epoch=80)
```
