### ISSUE TITLE
Scripts query

### ISSUE THREAD

**Issue by HamDan1999** [leondgarse/Keras_insightface#98]
Hey,

My current research is inspired by your work thanks a lot.

I have a question, do you have the scripts for getting the model's size (in MB), FLOPs, and inference time?
In addition, do you have MegaFace dataset evaluation script for Tensorflow models?

Thanks a lot for your beautiful work.

**Comment by leondgarse** [comment]
- For model size, you can simply check using `model.summary()`.
- For FLOPs, you can calculate using my another repo [keras_cv_attention_models](https://github.com/leondgarse/keras_cv_attention_models):
  ```py
  !pip install keras-cv-attention-models
  from keras_cv_attention_models import model_surgery
  model_surgery.get_flops({your_loaded_model})
  ```
- For inference time, basically you may use `%timeit` in `ipython`:
  ```py
  %timeit model(tf.random.uniform([{max_batch_size_on_your_device}, 112, 112, 3]))
  ```
  or write a timer by yourself. I don't have a ready one on hand either...
- For MegaFace dataset, I don't have the TF version either. Actually I'm not very familliar with it, but if it supports onnx, you may convert a Keras model to onnx using [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx).

**Comment by HamDan1999** [comment]
Thanks a lot!
Much appreciated.
